<?php
declare(strict_types=1);
final class AiCostAttributionReviewTest extends WP_UnitTestCase {
 protected function setUp():void{parent::setUp();DigiForge\Core\Activator::activate();wp_set_current_user(self::factory()->user->create(['role'=>'administrator']));}
 private function fixture():array {
  global $wpdb;$t=DigiForge\Database\Tables::class;$now=current_time('mysql',true);$gov=new DigiForge\AI\ShopAiGovernanceRepository();$gov->savePolicy(['shop_key'=>'digital','currency'=>'USD','stages'=>['develop'=>['limit'=>10]]]);$usage=$gov->reserveGeneration('digital','develop',wp_generate_uuid4());self::assertNotWPError($usage);
  $wpdb->insert($t::opportunities(),['title'=>'Offline attribution','state'=>'APPROVED','created_at'=>$now,'updated_at'=>$now]);$opportunity=(int)$wpdb->insert_id;$wpdb->insert($t::research_candidates(),['title'=>'Offline candidate','canonical_title'=>'offline','fingerprint'=>hash('sha256',wp_generate_uuid4()),'summary'=>'Offline','score_version'=>'v1','score_inputs'=>wp_json_encode(['shop_key'=>'digital']),'review_status'=>'APPROVED','opportunity_id'=>$opportunity,'created_at'=>$now,'updated_at'=>$now]);
  $wpdb->insert($t::product_families(),['opportunity_id'=>$opportunity,'name'=>'Offline family','created_at'=>$now,'updated_at'=>$now]);$family=(int)$wpdb->insert_id;$wpdb->insert($t::products(),['product_family_id'=>$family,'name'=>'Offline product','created_at'=>$now,'updated_at'=>$now]);return [$usage,(int)$wpdb->insert_id];
 }
 public function testLateProductAttributionIsAppendOnlyAndScoped():void {[$usage,$product]=$this->fixture();$repo=new DigiForge\AI\CostAttributionRepository();$r=$repo->review((int)$usage['id'],'digital',['product_id'=>$product],'CONFIRM_COST_ATTRIBUTION');self::assertNotWPError($r);self::assertSame($product,$r['product_id']);self::assertTrue($repo->review((int)$usage['id'],'digital',['product_id'=>$product],'CONFIRM_COST_ATTRIBUTION')['idempotent_replay']);self::assertWPError($repo->review((int)$usage['id'],'jewelry',['product_id'=>$product],'CONFIRM_COST_ATTRIBUTION'));global $wpdb;self::assertSame('0',(string)$wpdb->get_var($wpdb->prepare('SELECT product_id FROM '.DigiForge\Database\Tables::shop_ai_usage().' WHERE id=%d',$usage['id'])));$snapshot=(new DigiForge\AI\ProviderEvidenceRepository())->snapshot((int)$usage['id'],'digital');self::assertSame($product,$snapshot['attribution']['product_id']);}
 public function testLateAttributionRequiresHumanDecisionAndCannotBeReassigned():void {[$usage,$product]=$this->fixture();$repo=new DigiForge\AI\CostAttributionRepository();self::assertWPError($repo->review((int)$usage['id'],'digital',['product_id'=>$product],''));self::assertNotWPError($repo->review((int)$usage['id'],'digital',['product_id'=>$product],'CONFIRM_COST_ATTRIBUTION'));self::assertWPError($repo->review((int)$usage['id'],'digital',['product_id'=>999999],'CONFIRM_COST_ATTRIBUTION'));wp_set_current_user(0);self::assertWPError($repo->review((int)$usage['id'],'digital',['product_id'=>$product],'CONFIRM_COST_ATTRIBUTION'));}
}
