<?php
declare(strict_types=1);
final class AiEvidenceWorkflowTest extends WP_UnitTestCase {
 protected function setUp():void {parent::setUp();DigiForge\Core\Activator::activate();wp_set_current_user(self::factory()->user->create(['role'=>'administrator']));}
 private function request(array $body,string $route):WP_REST_Request {$r=new WP_REST_Request('POST',$route);$r->set_header('Content-Type','application/json');$r->set_body((string)wp_json_encode($body));return $r;}
 public function testRealRestBoundaryRequiresCapabilityAndExplicitReview():void {$controller=new DigiForge\REST\AiEvidenceController();$controller->register();do_action('rest_api_init');wp_set_current_user(0);$r=rest_do_request($this->request(['shop_key'=>'digital'],'/digiforge/v1/ai/evidence/quotes'));self::assertSame(401,$r->get_status());wp_set_current_user(self::factory()->user->create(['role'=>'subscriber']));$r=rest_do_request($this->request(['shop_key'=>'digital'],'/digiforge/v1/ai/evidence/quotes'));self::assertSame(403,$r->get_status());wp_set_current_user(self::factory()->user->create(['role'=>'administrator']));$r=rest_do_request($this->request(['shop_key'=>'all','decision'=>'CONFIRM_PROVIDER_QUOTE'],'/digiforge/v1/ai/evidence/quotes'));self::assertSame(400,$r->get_status());}
 public function testReviewedQuoteRestReplayAndConflictNeverExecuteHttp():void {$c=new DigiForge\REST\AiEvidenceController();$c->register();do_action('rest_api_init');$http=0;$filter=static function($pre)use(&$http){$http++;return new WP_Error('forbidden');};add_filter('pre_http_request',$filter);try{$q=['provider'=>'openai','quote_id'=>'wf-'.wp_generate_uuid4(),'request_sha256'=>hash('sha256','fixture'),'model'=>'fixture','currency'=>'USD','maximum_charge'=>'0.100000','inclusive_all_charges'=>true,'valid_from'=>gmdate('Y-m-d\TH:i:s\Z',time()-60),'valid_until'=>gmdate('Y-m-d\TH:i:s\Z',time()+600)];$body=['shop_key'=>'digital','decision'=>'CONFIRM_PROVIDER_QUOTE','document'=>(string)wp_json_encode($q)];$r=rest_do_request($this->request($body,'/digiforge/v1/ai/evidence/quotes'));self::assertSame(200,$r->get_status());$r=rest_do_request($this->request($body,'/digiforge/v1/ai/evidence/quotes'));self::assertTrue($r->get_data()['idempotent_replay']);$body['shop_key']='jewelry';$r=rest_do_request($this->request($body,'/digiforge/v1/ai/evidence/quotes'));self::assertSame(409,$r->get_status());self::assertSame(0,$http);}finally{remove_filter('pre_http_request',$filter);}}
 public function testPortalFormHasNonceAndConcreteShopButNoExecutionControl():void {$workflow=new DigiForge\Portal\AiEvidenceWorkflow();ob_start();$workflow->render('digital');$html=(string)ob_get_clean();self::assertStringContainsString('Provider evidence review',$html);self::assertStringContainsString('_wpnonce',$html);self::assertStringContainsString('CONFIRM_PROVIDER_STATEMENT_CHARGE',$html);self::assertStringNotContainsString('Run AI',$html);ob_start();$workflow->render('all');$all=(string)ob_get_clean();self::assertStringNotContainsString('<form',$all);}
 public function testChargeWorkflowRequiresMatchingStoredResponseAndExplicitReview():void {$gov=new DigiForge\AI\ShopAiGovernanceRepository();$gov->savePolicy(['shop_key'=>'digital','currency'=>'USD','stages'=>['develop'=>['limit'=>10]]]);$usage=$gov->reserveGeneration('digital','develop',wp_generate_uuid4());self::assertNotWPError($usage);$response=['response_id'=>'resp_'.str_replace('-','',wp_generate_uuid4()),'status'=>'completed','model'=>'fixture','usage'=>['input_tokens'=>1,'output_tokens'=>1,'total_tokens'=>2]];$repo=new DigiForge\AI\ProviderEvidenceRepository();self::assertNotWPError($repo->recordOutcome((int)$usage['id'],'digital',$response));$wf=new DigiForge\Portal\AiEvidenceWorkflow();$p=['operation'=>'charge','shop_key'=>'digital','usage_id'=>$usage['id'],'decision'=>'CONFIRM_PROVIDER_STATEMENT_CHARGE','document'=>(string)wp_json_encode(['provider'=>'openai','invoice_id'=>'inv-'.wp_generate_uuid4(),'lines'=>[['line_id'=>'1','response_id'=>$response['response_id'],'model'=>'fixture','currency'=>'USD','amount'=>'0.100000']]])];self::assertNotWPError($wf->submit($p));self::assertTrue($wf->submit($p)['idempotent_replay']);$proof=$repo->snapshot((int)$usage['id'],'digital')['settlement'];self::assertSame($p['document'],$proof['source_document']);self::assertSame(hash('sha256',$proof['source_document']),$proof['charge']['source_sha256']);$p['shop_key']='jewelry';self::assertWPError($wf->submit($p));$p['shop_key']='digital';$p['decision']='';self::assertWPError($wf->submit($p));}
 public function testRealBrowserHandlersReturnVisiblePortalErrorAndCorrectPage():void {
  $page=self::factory()->post->create(['post_type'=>'page','post_status'=>'publish','post_title'=>'Operator portal']);$before=$_POST;$_POST=['shop_key'=>'digital','return_url'=>get_permalink($page)];$location='';$filter=static function(string $url)use(&$location):string{$location=$url;throw new RuntimeException('captured redirect');};add_filter('wp_redirect',$filter);
  try{foreach([new DigiForge\Portal\AiEvidenceWorkflow(),new DigiForge\POD\DeterministicRenderWorkflow()]as $workflow){try{$workflow->handle();}catch(RuntimeException $e){self::assertSame('captured redirect',$e->getMessage());}parse_str((string)parse_url($location,PHP_URL_QUERY),$query);self::assertArrayHasKey('df_message',$query);self::assertSame((string)$page,(string)($query['page_id']??''));$get=$_GET;try{$_GET=$query;$html=(new DigiForge\Portal\Portal())->render();self::assertStringContainsString('role="alert"',$html);self::assertStringContainsString(esc_html($query['df_message']),$html);}finally{$_GET=$get;}}}finally{remove_filter('wp_redirect',$filter);$_POST=$before;}
 }
 public function testNonceAndReturnTargetsFailClosedWithoutChangingControls():void {
  DigiForge\Core\Settings::protectProduction();$before=[DigiForge\Core\Settings::get('stop_all',true),DigiForge\Core\Settings::safety_locked(),DigiForge\Core\Settings::get('automation_armed',false)];$wf=new DigiForge\Portal\AiEvidenceWorkflow();self::assertWPError($wf->processBrowser(['shop_key'=>'digital','_wpnonce'=>'invalid']));self::assertWPError((new DigiForge\POD\DeterministicRenderWorkflow())->processBrowser(['_wpnonce'=>'invalid']));self::assertSame(home_url('/'),DigiForge\Portal\OperatorReturnUrl::resolve('https://example.invalid/'));self::assertSame($before,[DigiForge\Core\Settings::get('stop_all',true),DigiForge\Core\Settings::safety_locked(),DigiForge\Core\Settings::get('automation_armed',false)]);
 }
 public function testRealRenderRouteDeniesAnonymousAndWrongShop():void {(new DigiForge\POD\DeterministicRenderWorkflow())->register();do_action('rest_api_init');wp_set_current_user(0);$r=rest_do_request($this->request(['shop_key'=>'personalized_pod','decision'=>'PREPARE_LOCAL_ARTIFACTS'],'/digiforge/v1/pod/local-render'));self::assertSame(401,$r->get_status());wp_set_current_user(self::factory()->user->create(['role'=>'administrator']));$r=rest_do_request($this->request(['shop_key'=>'digital','decision'=>'PREPARE_LOCAL_ARTIFACTS'],'/digiforge/v1/pod/local-render'));self::assertSame(409,$r->get_status());}
}
