<?php
declare(strict_types=1);
final class AiMonetaryReservationTest extends WP_UnitTestCase {
 private string $shop;private string $requestHash;
 protected function setUp():void {parent::setUp();DigiForge\Core\Activator::activate();wp_set_current_user(self::factory()->user->create(['role'=>'administrator']));$this->shop='money-'.substr(wp_generate_uuid4(),0,8);$this->requestHash=hash('sha256','offline exact request');$this->policy();}
 private function policy(string $budget='1.000000'):void {(new DigiForge\AI\ShopAiGovernanceRepository())->savePolicy(['shop_key'=>$this->shop,'currency'=>'USD','budgets'=>['month'=>$budget],'stages'=>['develop'=>['limit'=>10]]]);}
 private function quote(string $amount='0.600000'):array {return ['provider'=>'openai','quote_id'=>'q-'.wp_generate_uuid4(),'request_sha256'=>$this->requestHash,'model'=>'fixture-model','currency'=>'USD','maximum_charge'=>$amount,'inclusive_all_charges'=>true,'valid_from'=>gmdate('Y-m-d\TH:i:s\Z',time()-60),'valid_until'=>gmdate('Y-m-d\TH:i:s\Z',time()+3600)];}
 private function review(array $q):array|WP_Error {return (new DigiForge\AI\MonetaryReservationRepository())->reviewQuote($this->shop,(string)wp_json_encode($q),'CONFIRM_PROVIDER_QUOTE');}
 private function reserve(array $q,string $key=''):array|WP_Error {return (new DigiForge\AI\ShopAiGovernanceRepository())->reserveGeneration($this->shop,'develop',$key?:wp_generate_uuid4(),null,['quote_id'=>$q['quote_id'],'request_sha256'=>$this->requestHash,'model'=>$q['model']]);}
 public function testAuthoritativeQuoteAndOutstandingCeilingEnforceBudget():void {$q=$this->quote();$proof=$this->review($q);self::assertNotWPError($proof);$one=$this->reserve($q);self::assertNotWPError($one);self::assertSame('0.600000',$one['estimated_cost']);$two=$this->reserve($q);self::assertWPError($two);self::assertSame('ai_money_budget_ceiling',$two->get_error_code());}
 public function testExpiredOrWrongRequestQuoteFailsClosed():void {$q=$this->quote();$q['valid_until']=gmdate('Y-m-d\TH:i:s\Z',time()-1);self::assertWPError($this->review($q));$q=$this->quote();self::assertNotWPError($this->review($q));$this->requestHash=hash('sha256','another request');self::assertWPError($this->reserve($q));}
 public function testQuoteRequiresExplicitHumanReviewAndIsImmutable():void {$q=$this->quote();self::assertWPError((new DigiForge\AI\MonetaryReservationRepository())->reviewQuote($this->shop,(string)wp_json_encode($q),''));self::assertNotWPError($this->review($q));self::assertTrue($this->review($q)['idempotent_replay']);$q['maximum_charge']='0.100000';self::assertWPError($this->review($q));wp_set_current_user(0);self::assertWPError($this->review($this->quote()));}
 public function testReservedReplayCannotChangeRequestOrShop():void {$this->policy('5');$q=$this->quote();self::assertNotWPError($this->review($q));$key=wp_generate_uuid4();$one=$this->reserve($q,$key);self::assertNotWPError($one);self::assertTrue($this->reserve($q,$key)['idempotent_replay']);$q2=$this->quote('0.700000');self::assertNotWPError($this->review($q2));self::assertWPError($this->reserve($q2,$key));$other=(new DigiForge\AI\ShopAiGovernanceRepository())->reserveGeneration('other','develop',$key,null,['quote_id'=>$q['quote_id'],'request_sha256'=>$this->requestHash,'model'=>$q['model']]);self::assertWPError($other);}
 public function testHistoricalUnboundedReservationBlocksMonetaryAccounting():void {$gov=new DigiForge\AI\ShopAiGovernanceRepository();$gov->recordUsage(['shop_key'=>$this->shop,'stage'=>'develop','currency'=>'USD'],'generation-legacy-'.wp_generate_uuid4());$q=$this->quote();self::assertNotWPError($this->review($q));self::assertWPError($this->reserve($q));}
 public function testOldPendingHoldStillConsumesCurrentBudget():void {$q=$this->quote();self::assertNotWPError($this->review($q));$one=$this->reserve($q);self::assertNotWPError($one);global $wpdb;$wpdb->update(DigiForge\Database\Tables::shop_ai_usage(),['occurred_at'=>'2020-01-01 00:00:00'],['id'=>$one['id']]);self::assertWPError($this->reserve($q));}
 public function testPendingProjectionFailureCannotAuthorizeAProviderAttempt():void {$q=$this->quote();self::assertNotWPError($this->review($q));global $wpdb;$table=DigiForge\Database\Tables::shop_ai_usage();$filter=static fn(string $sql):string=>str_starts_with($sql,'INSERT INTO `'.$table.'`')?'SELECT * FROM digiforge_missing_money_projection':$sql;add_filter('query',$filter);try{$r=$this->reserve($q);}finally{remove_filter('query',$filter);}self::assertWPError($r);}
 public function testIntegerDecimalBoundariesDoNotLoseMicroUnits():void {self::assertSame(1000001,DigiForge\AI\MonetaryReservationRepository::micros('1.000001'));foreach(['NaN','1e2','-1','0.0000001','999999999999']as $invalid){self::assertWPError(DigiForge\AI\MonetaryReservationRepository::micros($invalid));}}
 public function testShopLockContentionBlocksSecondConnection():void {$q=$this->quote();self::assertNotWPError($this->review($q));global $wpdb;$second=new wpdb(DB_USER,DB_PASSWORD,DB_NAME,DB_HOST);$lock=DigiForge\AI\ShopAiGovernanceRepository::generationLockName($this->shop);self::assertSame('1',(string)$second->get_var($second->prepare('SELECT GET_LOCK(%s,0)',$lock)));try{self::assertWPError($this->reserve($q));}finally{$second->get_var($second->prepare('SELECT RELEASE_LOCK(%s)',$lock));$second->close();}self::assertNotWPError($this->reserve($q));}
 public function testActualChargeReleasesOnlyItsOutstandingCeilingAndOverrunBlocksNextRequest():void {
  $q=$this->quote();self::assertNotWPError($this->review($q));$usage=$this->reserve($q);self::assertNotWPError($usage);$repo=new DigiForge\AI\ProviderEvidenceRepository();$response=['response_id'=>'resp_'.str_replace('-','',wp_generate_uuid4()),'status'=>'completed','model'=>'fixture-model','usage'=>['input_tokens'=>1,'output_tokens'=>1,'total_tokens'=>2]];self::assertNotWPError($repo->recordOutcome((int)$usage['id'],$this->shop,$response));$charge=['source'=>'provider_statement','source_sha256'=>hash('sha256','synthetic statement'),'invoice_id'=>'invoice-'.wp_generate_uuid4(),'line_id'=>'1','response_id'=>$response['response_id'],'model'=>'fixture-model','currency'=>'USD','amount'=>'0.200000'];$charge=$this->statement($charge);self::assertNotWPError($repo->settle((int)$usage['id'],$this->shop,$charge));$two=$this->reserve($q);self::assertNotWPError($two);$response['response_id']='resp_'.str_replace('-','',wp_generate_uuid4());self::assertNotWPError($repo->recordOutcome((int)$two['id'],$this->shop,$response));$charge['response_id']=$response['response_id'];$charge['line_id']='2';$charge['amount']='0.900000';$charge=$this->statement($charge);self::assertWPError($repo->settle((int)$two['id'],$this->shop,$charge));self::assertWPError($repo->settle((int)$two['id'],$this->shop,$charge));self::assertSame('RESERVATION_BOUND_EXCEEDED',$repo->snapshot((int)$two['id'],$this->shop)['cost_state']);self::assertWPError($this->reserve($q));
 }
 public function testBoundedRequestFingerprintIsTheActualProviderEnvelope():void {
  $contract=DigiForge\Launch\OpenAIClient::generationContract('hello',8000,false);self::assertSame(hash('sha256',(string)wp_json_encode(['model'=>'gpt-5.6-luna','input'=>'hello','max_output_tokens'=>8000,'text'=>['format'=>['type'=>'json_object']]])),$contract['request_sha256']);self::assertArrayNotHasKey('input',$contract);
 }
 public function testProductOrOrderAttributionCannotUseAnUnownedIdentifier():void {$q=$this->quote();self::assertNotWPError($this->review($q));$r=(new DigiForge\AI\ShopAiGovernanceRepository())->reserveGeneration($this->shop,'develop',wp_generate_uuid4(),null,['quote_id'=>$q['quote_id'],'request_sha256'=>$this->requestHash,'model'=>$q['model'],'product_id'=>999999,'order_id'=>999999]);self::assertWPError($r);}
 private function order(string $shop):int {global $wpdb;$now=current_time('mysql',true);$wpdb->insert(DigiForge\Database\Tables::orders(),['channel'=>'etsy','environment'=>'sandbox','external_order_reference'=>wp_generate_uuid4(),'shop_reference'=>$shop,'currency'=>'USD','state'=>'RECEIVED','created_at'=>$now,'updated_at'=>$now]);return (int)$wpdb->insert_id;}
 public function testZeroBudgetGenerationStillBindsExplicitStoredOrderAttribution():void {$this->policy('0');$order=$this->order($this->shop);$method=new ReflectionMethod(DigiForge\AI\GovernedGeneration::class,'execute');$r=$method->invoke(new DigiForge\AI\GovernedGeneration(),$this->shop,'develop',wp_generate_uuid4(),null,fn()=>['response_id'=>'resp_'.str_replace('-','',wp_generate_uuid4()),'status'=>'completed','model'=>'fixture-model','usage'=>['input_tokens'=>1,'output_tokens'=>1,'total_tokens'=>2]],['order_id'=>$order]);self::assertNotWPError($r);$snapshot=(new DigiForge\AI\ProviderEvidenceRepository())->snapshot((int)$r['ai_usage_id'],$this->shop);self::assertSame($order,$snapshot['metering']['order_id']);}
 public function testNumericOrderIdentityRequiresVerifiedSameEnvironmentBusiness():void {$this->shop='personalized_pod';$this->policy();$q=$this->quote();self::assertNotWPError($this->review($q));$order=$this->order('68031896');$gov=new DigiForge\AI\ShopAiGovernanceRepository();$contract=['quote_id'=>$q['quote_id'],'request_sha256'=>$this->requestHash,'model'=>$q['model'],'order_id'=>$order];self::assertWPError($gov->reserveGeneration($this->shop,'develop',wp_generate_uuid4(),null,$contract));global $wpdb;$now=current_time('mysql',true);$wpdb->insert(DigiForge\Database\Tables::integrations(),['provider'=>'etsy','environment'=>'sandbox','connection_key'=>'money-fixture-'.wp_generate_uuid4(),'display_name'=>'Offline identity','status'=>'CONFIGURED','enabled'=>0,'config'=>wp_json_encode(['_connection_test'=>['ok'=>true,'details'=>['shop_id'=>68031896,'shop_name'=>'DigicraftifyShop']]]),'created_at'=>$now,'updated_at'=>$now]);self::assertNotWPError($gov->reserveGeneration($this->shop,'develop',wp_generate_uuid4(),null,$contract));}
 public function testConcurrentPolicyEditUsesTheGenerationAccountingLock():void {global $wpdb;$second=new wpdb(DB_USER,DB_PASSWORD,DB_NAME,DB_HOST);$lock=DigiForge\AI\ShopAiGovernanceRepository::generationLockName($this->shop);$second->get_var($second->prepare('SELECT GET_LOCK(%s,0)',$lock));try{$r=(new DigiForge\AI\ShopAiGovernanceRepository())->savePolicy(['shop_key'=>$this->shop,'currency'=>'USD']);self::assertWPError($r);}finally{$second->get_var($second->prepare('SELECT RELEASE_LOCK(%s)',$lock));$second->close();}}
 public function testDifferentProviderModelPreservesMeteringButBlocksBoundedCostOutcome():void {$q=$this->quote();self::assertNotWPError($this->review($q));$usage=$this->reserve($q);self::assertNotWPError($usage);$repo=new DigiForge\AI\ProviderEvidenceRepository();$r=$repo->recordOutcome((int)$usage['id'],$this->shop,['response_id'=>'resp_'.str_replace('-','',wp_generate_uuid4()),'status'=>'completed','model'=>'different-provider-model','usage'=>['input_tokens'=>1,'output_tokens'=>1,'total_tokens'=>2]]);self::assertWPError($r);$snapshot=$repo->snapshot((int)$usage['id'],$this->shop);self::assertSame('different-provider-model',$snapshot['metering']['model']);self::assertSame('RECONCILIATION_REQUIRED',$snapshot['cost_state']);self::assertWPError($this->reserve($q));}
 public function testReviewedTariffDerivesOnlyAnUpperBoundNeverAnActualCharge():void {
  $contract=DigiForge\Launch\OpenAIClient::generationContract('tariff fixture',1000,false,true);$tariff=['provider'=>'openai','tariff_id'=>'tariff-'.wp_generate_uuid4(),'model'=>$contract['model'],'currency'=>'USD','input_per_million'=>'2.000000','output_per_million'=>'8.000000','maximum_billable_input_tokens'=>100000,'search_per_call_maximum'=>'0.020000','inclusive_all_charges'=>true,'valid_from'=>gmdate('Y-m-d\TH:i:s\Z',time()-60),'valid_until'=>gmdate('Y-m-d\TH:i:s\Z',time()+600)];$repo=new DigiForge\AI\MonetaryReservationRepository();self::assertNotWPError($repo->reviewTariff($this->shop,(string)wp_json_encode($tariff),'CONFIRM_PROVIDER_TARIFF'));$q=$repo->findQuote($this->shop,$contract);self::assertNotWPError($q);$usage=(new DigiForge\AI\ShopAiGovernanceRepository())->reserveGeneration($this->shop,'develop',wp_generate_uuid4(),null,$q);self::assertNotWPError($usage);self::assertSame('0.228000',$usage['estimated_cost']);self::assertSame('0.000000',$usage['actual_cost']);self::assertSame(1,$contract['web_search_call_limit']);
 }
 public function testTariffCannotIgnoreToolsOrClaimUnlimitedInput():void {$repo=new DigiForge\AI\MonetaryReservationRepository();self::assertWPError($repo->reviewTariff($this->shop,(string)wp_json_encode(['provider'=>'openai','maximum_billable_input_tokens'=>0]),'CONFIRM_PROVIDER_TARIFF'));$contract=DigiForge\Launch\OpenAIClient::generationContract('x',1000,false,true);self::assertWPError($repo->findQuote($this->shop,$contract));}
 public function testTariffMeteringBeyondReviewedTokenLimitIsRetainedAndBlocksReplay():void {
  $contract=DigiForge\Launch\OpenAIClient::generationContract('bounded tokens',1000);$tariff=['provider'=>'openai','tariff_id'=>'tariff-'.wp_generate_uuid4(),'model'=>$contract['model'],'currency'=>'USD','input_per_million'=>'2.000000','output_per_million'=>'8.000000','maximum_billable_input_tokens'=>100000,'search_per_call_maximum'=>'0.020000','inclusive_all_charges'=>true,'valid_from'=>gmdate('Y-m-d\TH:i:s\Z',time()-60),'valid_until'=>gmdate('Y-m-d\TH:i:s\Z',time()+600)];$repo=new DigiForge\AI\MonetaryReservationRepository();self::assertNotWPError($repo->reviewTariff($this->shop,(string)wp_json_encode($tariff),'CONFIRM_PROVIDER_TARIFF'));$quote=$repo->findQuote($this->shop,$contract);$usage=(new DigiForge\AI\ShopAiGovernanceRepository())->reserveGeneration($this->shop,'develop',wp_generate_uuid4(),null,$quote);self::assertNotWPError($usage);$meter=['response_id'=>'resp_'.str_replace('-','',wp_generate_uuid4()),'status'=>'completed','model'=>$contract['model'],'usage'=>['input_tokens'=>100001,'output_tokens'=>1,'total_tokens'=>100002]];$provider=new DigiForge\AI\ProviderEvidenceRepository();self::assertWPError($provider->recordOutcome((int)$usage['id'],$this->shop,$meter));self::assertWPError($provider->recordOutcome((int)$usage['id'],$this->shop,$meter));$snapshot=$provider->snapshot((int)$usage['id'],$this->shop);self::assertSame(100001,$snapshot['metering']['usage']['input_tokens']);self::assertSame('RECONCILIATION_REQUIRED',$snapshot['cost_state']);self::assertWPError((new DigiForge\AI\ShopAiGovernanceRepository())->reserveGeneration($this->shop,'develop',wp_generate_uuid4(),null,$quote));
 }

 public function testSeparateCostContextBindsStoredOrderIntoMonetaryHold():void {$q=$this->quote();self::assertNotWPError($this->review($q));$order=$this->order($this->shop);$usage=(new DigiForge\AI\ShopAiGovernanceRepository())->reserveGeneration($this->shop,'develop',wp_generate_uuid4(),null,['quote_id'=>$q['quote_id'],'request_sha256'=>$this->requestHash,'model'=>$q['model']],['order_id'=>$order]);self::assertNotWPError($usage);self::assertSame($order,(int)$usage['order_id']);$hold=(new DigiForge\AI\MonetaryReservationRepository())->reservation((int)$usage['id']);self::assertSame($order,$hold['order_id']);}

 public function testHashOnlyChargeCannotReleaseAnAuthoritativeMonetaryHold():void {$q=$this->quote();self::assertNotWPError($this->review($q));$usage=$this->reserve($q);$repo=new DigiForge\AI\ProviderEvidenceRepository();$response=['response_id'=>'resp_'.str_replace('-','',wp_generate_uuid4()),'status'=>'completed','model'=>'fixture-model','usage'=>['input_tokens'=>1,'output_tokens'=>1,'total_tokens'=>2]];self::assertNotWPError($repo->recordOutcome((int)$usage['id'],$this->shop,$response));$charge=['source'=>'provider_statement','source_sha256'=>hash('sha256','caller hash only'),'invoice_id'=>'invoice-'.wp_generate_uuid4(),'line_id'=>'1','response_id'=>$response['response_id'],'model'=>'fixture-model','currency'=>'USD','amount'=>'0.200000'];self::assertWPError($repo->settle((int)$usage['id'],$this->shop,$charge));self::assertSame('AWAITING_PROVIDER_CHARGE',$repo->snapshot((int)$usage['id'],$this->shop)['cost_state']);self::assertWPError($this->reserve($q));}
 private function statement(array $charge):array {$document=(string)wp_json_encode(['provider'=>'openai','invoice_id'=>$charge['invoice_id'],'lines'=>[['line_id'=>$charge['line_id'],'response_id'=>$charge['response_id'],'model'=>$charge['model'],'currency'=>$charge['currency'],'amount'=>$charge['amount']]]]);$charge['source_document']=$document;$charge['source_sha256']=hash('sha256',$document);return $charge;}

 public function testPartialHoldLinkCannotPromoteLegacyHashOnlySettlementReplay():void {$q=$this->quote();self::assertNotWPError($this->review($q));$usage=$this->reserve($q);$money=new DigiForge\AI\MonetaryReservationRepository();$hold=$money->reservation((int)$usage['id']);delete_option('digiforge_ai_money_usage_'.$usage['id']);$repo=new DigiForge\AI\ProviderEvidenceRepository();$response=['response_id'=>'resp_'.str_replace('-','',wp_generate_uuid4()),'status'=>'completed','model'=>'fixture-model','usage'=>['input_tokens'=>1,'output_tokens'=>1,'total_tokens'=>2]];self::assertNotWPError($repo->recordOutcome((int)$usage['id'],$this->shop,$response));$charge=$this->statement(['source'=>'provider_statement','invoice_id'=>'invoice-'.wp_generate_uuid4(),'line_id'=>'1','response_id'=>$response['response_id'],'model'=>'fixture-model','currency'=>'USD','amount'=>'0.200000']);$legacy=$charge;unset($legacy['source_document']);self::assertNotWPError($repo->settle((int)$usage['id'],$this->shop,$legacy));self::assertNotWPError($money->link($usage,$hold));self::assertSame('RECONCILIATION_REQUIRED',$repo->snapshot((int)$usage['id'],$this->shop)['cost_state']);self::assertWPError($repo->settle((int)$usage['id'],$this->shop,$charge));}

}
