<?php
declare(strict_types=1);
final class AiProviderSettlementTest extends WP_UnitTestCase {
 private array $usage;
 private string $shop;
 public function setUp():void {parent::setUp();DigiForge\Core\Activator::activate();wp_set_current_user(self::factory()->user->create(['role'=>'administrator']));$this->shop='settle-'.wp_rand();$r=new DigiForge\AI\ShopAiGovernanceRepository();self::assertFalse(is_wp_error($r->savePolicy(['shop_key'=>$this->shop,'currency'=>'USD','stages'=>['develop'=>['limit'=>8]]])));$this->usage=$r->reserveGeneration($this->shop,'develop','attempt-'.wp_generate_uuid4());self::assertFalse(is_wp_error($this->usage));}
 private function response():array{return ['response_id'=>'resp_'.str_replace('-','',wp_generate_uuid4()),'model'=>'fixture-model','usage'=>['input_tokens'=>20,'output_tokens'=>10,'total_tokens'=>30],'payload'=>['fixture'=>true]];}
 private function charge(array $response):array{return ['response_id'=>$response['response_id'],'model'=>$response['model'],'source'=>'provider_statement','source_sha256'=>hash('sha256','LOCAL SYNTHETIC STATEMENT NOT REAL SPEND'),'invoice_id'=>'fixture-'.wp_generate_uuid4(),'line_id'=>'line1','amount'=>'0.012345','currency'=>'USD'];}
 public function testProviderMeteringAndReviewedChargeAreSeparateImmutableEvidence():void {
  $r=new DigiForge\AI\ProviderEvidenceRepository();$response=$this->response();$meter=$r->recordOutcome((int)$this->usage['id'],$this->shop,$response);self::assertFalse(is_wp_error($meter));self::assertSame(30,$meter['usage']['total_tokens']);self::assertSame('AWAITING_PROVIDER_CHARGE',$meter['cost_state']);
  $before=(new DigiForge\AI\ShopAiGovernanceRepository())->evaluate($this->shop);self::assertSame(0.0,$before['actual']['costs']['month']??0.0);
  $charge=$this->charge($response);$saved=$r->settle((int)$this->usage['id'],$this->shop,$charge);self::assertFalse(is_wp_error($saved));self::assertSame('REVIEWED_PROVIDER_CHARGE',$saved['cost_state']);$same=$r->settle((int)$this->usage['id'],$this->shop,$charge);self::assertTrue($same['idempotent_replay']);
  global $wpdb;self::assertSame('0.012345',$wpdb->get_var($wpdb->prepare('SELECT actual_cost FROM '.DigiForge\Database\Tables::shop_ai_usage().' WHERE id=%d',$this->usage['id'])));$charge['amount']='0.020000';$conflict=$r->settle((int)$this->usage['id'],$this->shop,$charge);self::assertTrue(is_wp_error($conflict));self::assertSame('ai_evidence_conflict',$conflict->get_error_code());
 }
 public function testCrossShopAndMalformedMeteringFailClosed():void {$r=new DigiForge\AI\ProviderEvidenceRepository();$response=$this->response();self::assertTrue(is_wp_error($r->recordOutcome((int)$this->usage['id'],'other',$response)));$response['usage']['total_tokens']=31;self::assertTrue(is_wp_error($r->recordOutcome((int)$this->usage['id'],$this->shop,$response)));}
 public function testQueuedBindingSupportsExactBackgroundCompletion():void {$r=new DigiForge\AI\ProviderEvidenceRepository();$response=$this->response();$queued=$r->recordOutcome((int)$this->usage['id'],$this->shop,['response_id'=>$response['response_id'],'status'=>'queued']);self::assertFalse(is_wp_error($queued));self::assertSame('PENDING_PROVIDER_COMPLETION',$queued['cost_state']);$done=$r->completeByResponse($response);self::assertFalse(is_wp_error($done));self::assertSame($this->shop,$done['shop_key']);$changed=$response;$changed['usage']=['input_tokens'=>10,'output_tokens'=>20,'total_tokens'=>30];self::assertTrue(is_wp_error($r->completeByResponse($changed)));}
 public function testProviderResponseCannotBeBoundToAnotherReservation():void {$r=new DigiForge\AI\ProviderEvidenceRepository();$response=$this->response();self::assertFalse(is_wp_error($r->recordOutcome((int)$this->usage['id'],$this->shop,$response)));$other=(new DigiForge\AI\ShopAiGovernanceRepository())->reserveGeneration($this->shop,'develop','another-'.wp_generate_uuid4());self::assertTrue(is_wp_error($r->recordOutcome((int)$other['id'],$this->shop,$response)));}
 public function testChargeNeedsHumanEvidenceAndExactCurrency():void {$r=new DigiForge\AI\ProviderEvidenceRepository();$response=$this->response();self::assertFalse(is_wp_error($r->recordOutcome((int)$this->usage['id'],$this->shop,$response)));$charge=$this->charge($response);$charge['currency']='EUR';self::assertTrue(is_wp_error($r->settle((int)$this->usage['id'],$this->shop,$charge)));$charge['currency']='USD';wp_set_current_user(0);self::assertTrue(is_wp_error($r->settle((int)$this->usage['id'],$this->shop,$charge)));}
 public function testSettlementDoesNotEnableMonetaryGeneration():void {$r=new DigiForge\AI\ProviderEvidenceRepository();$response=$this->response();$r->recordOutcome((int)$this->usage['id'],$this->shop,$response);self::assertFalse(is_wp_error($r->settle((int)$this->usage['id'],$this->shop,$this->charge($response))));$gov=new DigiForge\AI\ShopAiGovernanceRepository();$gov->savePolicy(['shop_key'=>$this->shop,'currency'=>'USD','budgets'=>['month'=>1],'stages'=>['develop'=>['limit'=>8]]]);$blocked=$gov->reserveGeneration($this->shop,'develop','budget-'.wp_generate_uuid4());self::assertTrue(is_wp_error($blocked));self::assertSame('ai_generation_cost_accounting_unavailable',$blocked->get_error_code());}
 public function testGovernedProviderResponsePersistsMeteringBeforeReturningPayload():void {
  $response=$this->response();$calls=0;$method=new ReflectionMethod(DigiForge\AI\GovernedGeneration::class,'execute');
  $result=$method->invoke(new DigiForge\AI\GovernedGeneration(),$this->shop,'develop','boundary-'.wp_generate_uuid4(),null,function()use($response,&$calls):array{$calls++;return $response;});
  self::assertFalse(is_wp_error($result));self::assertSame(1,$calls);self::assertArrayHasKey('ai_usage_id',$result);$receipt=(new DigiForge\AI\ProviderEvidenceRepository())->snapshot((int)$result['ai_usage_id'],$this->shop);self::assertSame($response['response_id'],$receipt['metering']['response_id']);self::assertSame('AWAITING_PROVIDER_CHARGE',$receipt['cost_state']);
 }

 public function testProjectionFailurePreservesChargeProofAndRequiresReconciliation():void {
  $r=new DigiForge\AI\ProviderEvidenceRepository();$response=$this->response();$r->recordOutcome((int)$this->usage['id'],$this->shop,$response);$charge=$this->charge($response);$table=DigiForge\Database\Tables::shop_ai_usage();
  $filter=static fn(string $sql):string=>str_starts_with($sql,'UPDATE '.$table.' SET actual_cost=')?'SELECT * FROM digiforge_missing_cost_projection':$sql;add_filter('query',$filter);
  try{$failed=$r->settle((int)$this->usage['id'],$this->shop,$charge);}finally{remove_filter('query',$filter);}
  self::assertTrue(is_wp_error($failed));self::assertSame('ai_evidence_reconciliation_required',$failed->get_error_code());$state=$r->snapshot((int)$this->usage['id'],$this->shop);self::assertSame('RECONCILIATION_REQUIRED',$state['cost_state']);self::assertSame($charge['source_sha256'],$state['settlement']['charge']['source_sha256']);$again=$r->settle((int)$this->usage['id'],$this->shop,$charge);self::assertTrue(is_wp_error($again));self::assertSame('ai_evidence_reconciliation_required',$again->get_error_code());
 }
 public function testInvoiceLineCannotChargeTwoReservations():void {
  $r=new DigiForge\AI\ProviderEvidenceRepository();$one=$this->response();$r->recordOutcome((int)$this->usage['id'],$this->shop,$one);$charge=$this->charge($one);self::assertFalse(is_wp_error($r->settle((int)$this->usage['id'],$this->shop,$charge)));
  $other=(new DigiForge\AI\ShopAiGovernanceRepository())->reserveGeneration($this->shop,'develop','line-'.wp_generate_uuid4());$two=$this->response();$r->recordOutcome((int)$other['id'],$this->shop,$two);$charge['response_id']=$two['response_id'];$conflict=$r->settle((int)$other['id'],$this->shop,$charge);self::assertTrue(is_wp_error($conflict));self::assertSame('ai_evidence_conflict',$conflict->get_error_code());
 }

}
