<?php
declare(strict_types=1);
final class ProductionLifecycleHistoryReadModelTest extends WP_UnitTestCase{
 protected function setUp():void{parent::setUp();DigiForge\Core\Activator::activate();wp_set_current_user(self::factory()->user->create(['role'=>'administrator']));}
 public function testConsumedPermitMovesFromPendingToFailureHistory():void{$auth=hash('sha256','history-failure-auth');$nonce='history_failure_nonce_1234567890123';$nh=hash('sha256',$nonce);self::assertTrue(DigiForge\POD\ExecutionNonceLedger::consume($nonce,$auth,get_current_user_id()));$model=new DigiForge\POD\ProductionLifecycleHistoryReadModel();$pending=$model->project($auth);self::assertSame('CONSUMED_AWAITING_OUTCOME',$pending['lifecycle_state']);self::assertSame('AWAIT_TERMINAL_OUTCOME',$pending['operator_action']);$now=time();$record=['state'=>'EXECUTION_FAILED_RECORDED','failure_hash'=>hash('sha256','history-failure'),'failure'=>['action'=>'X','evidence_hash'=>hash('sha256','history-e'),'authorization_hash'=>$auth,'authorization_nonce_hash'=>$nh,'failure_category'=>'adapter_error','failure_code'=>'timeout','executed_by'=>get_current_user_id(),'recorded_at'=>$now,'nonce_consumed'=>true,'retry_permitted'=>false]];self::assertFalse(is_wp_error(DigiForge\POD\ExecutionFailureRepository::save($record)));$failed=$model->project($auth);self::assertSame('EXECUTION_FAILED',$failed['lifecycle_state']);self::assertSame('NONE',$failed['operator_action']);self::assertFalse($failed['retry_permitted']);}
 public function testRecentHistoryIsReadOnlyAndBounded():void{$x=(new DigiForge\POD\ProductionLifecycleHistoryReadModel())->recent(500);self::assertTrue($x['read_only']);self::assertFalse($x['retry_permitted']);self::assertFalse($x['external_execution_authorized']);self::assertLessThanOrEqual(200,$x['count']);}
 public function testUnknownHistoryMovesFromReconciliationToReviewToAcknowledged():void{global $wpdb;$auth=hash('sha256','history-unknown-auth');$unknown=hash('sha256','history-unknown');$fp=hash('sha256','history-unknown-fp');$now=current_time('mysql',true);$wpdb->insert(DigiForge\Database\Tables::pod_execution_unknowns(),['action'=>'X','evidence_hash'=>hash('sha256','history-unknown-e'),'authorization_hash'=>$auth,'nonce_hash'=>hash('sha256','history-unknown-n'),'failure_category'=>'ambiguous_transport','failure_code'=>'unknown','request_fingerprint'=>$fp,'reconciliation_identity'=>'{}','executed_by'=>get_current_user_id(),'recorded_at'=>$now,'unknown_hash'=>$unknown,'created_at'=>$now]);$wpdb->insert(DigiForge\Database\Tables::pod_execution_outcomes(),['authorization_hash'=>$auth,'outcome_type'=>'UNKNOWN','outcome_hash'=>$unknown,'created_at'=>$now]);$wpdb->insert(DigiForge\Database\Tables::pod_execution_nonces(),['nonce_hash'=>hash('sha256','history-unknown-n'),'authorization_hash'=>$auth,'consumed_by'=>get_current_user_id(),'consumed_at'=>$now]);$m=new DigiForge\POD\ProductionLifecycleHistoryReadModel();self::assertSame('EXECUTION_UNKNOWN_RECONCILIATION_REQUIRED',$m->project($auth)['lifecycle_state']);$result=['state'=>'PRINTIFY_RECONCILIATION_CONFIRMED','request_fingerprint'=>$fp,'provider_order_id'=>'p-history','provider_status'=>'created','http_status'=>200,'pagination_required'=>false,'pages_checked'=>1,'retry_permitted'=>false,'reconciliation_required'=>false];$rec=DigiForge\POD\PrintifyReconciliationRepository::save(['unknown'=>['authorization_hash'=>$auth,'unknown_hash'=>$unknown,'request_fingerprint'=>$fp]],$result,1);self::assertFalse(is_wp_error($rec));self::assertSame('EXECUTION_UNKNOWN_REVIEW_REQUIRED',$m->project($auth)['lifecycle_state']);$ack=DigiForge\POD\ReconciliationAcknowledgement::acknowledge($rec,get_current_user_id(),'ACKNOWLEDGE_CONFIRMED');self::assertFalse(is_wp_error($ack));self::assertFalse(is_wp_error(DigiForge\POD\ReconciliationAcknowledgementRepository::save($ack)));$done=$m->project($auth);self::assertSame('EXECUTION_UNKNOWN_ACKNOWLEDGED',$done['lifecycle_state']);self::assertSame('NONE',$done['operator_action']);self::assertFalse($done['retry_permitted']);}

}
