<?php
declare(strict_types=1);
final class ResearchShopIsolationTest extends WP_UnitTestCase {
 public function setUp():void {parent::setUp();DigiForge\Core\Activator::activate();wp_set_current_user(self::factory()->user->create(['role'=>'administrator']));}
 public function testSameTitleHasIndependentShopCandidatesAndReviews():void {$r=new DigiForge\Research\Repository();$title='Shared title '.wp_rand();$a=$r->createCandidate(['shop_key'=>'digital','title'=>$title],'same-key');$b=$r->createCandidate(['shop_key'=>'personalized_pod','title'=>$title],'same-key');self::assertFalse(is_wp_error($a));self::assertFalse(is_wp_error($b));self::assertNotSame($a['id'],$b['id']);$review=$r->review($a['id'],'APPROVED');self::assertFalse(is_wp_error($review));$bReplay=$r->createCandidate(['shop_key'=>'personalized_pod','title'=>$title]);self::assertSame('PENDING',$bReplay['review_status']);self::assertSame('personalized_pod',$bReplay['shop_key']);}
 public function testEvidenceCannotLinkAcrossShops():void {$r=new DigiForge\Research\Repository();$s=$r->createSource(['shop_key'=>'digital','name'=>'Fixture '.wp_rand()]);self::assertFalse(is_wp_error($s));$o=$r->ingest(['source_id'=>$s['id'],'title'=>'Observed '.wp_rand()]);self::assertFalse(is_wp_error($o));$e=$r->addEvidence($o['id'],['value'=>'Manual source evidence']);self::assertFalse(is_wp_error($e));$c=$r->createCandidate(['shop_key'=>'personalized_pod','title'=>'POD '.wp_rand()]);self::assertFalse(is_wp_error($c));$linked=$r->linkEvidence($c['id'],$e['id']);self::assertTrue(is_wp_error($linked));self::assertSame('digiforge_research_scope_mismatch',$linked->get_error_code());}
 public function testNewUnscopedResearchFailsClosed():void {$r=(new DigiForge\Research\Repository())->createCandidate(['title'=>'Unscoped '.wp_rand()]);self::assertTrue(is_wp_error($r));self::assertSame('digiforge_research_scope_required',$r->get_error_code());}
 public function testScopedListsAndDevelopmentContractPreserveOwner():void {$r=new DigiForge\Research\Repository();$title='Scoped '.wp_rand();$a=$r->createCandidate(['shop_key'=>'digital','title'=>$title]);$b=$r->createCandidate(['shop_key'=>'personalized_pod','title'=>$title]);$rows=$r->list('candidates',1,100,'digital');self::assertFalse(is_wp_error($rows));$ids=array_column($rows['items'],'id');self::assertContains($a['id'],$ids);self::assertNotContains($b['id'],$ids);self::assertTrue($r->assertCandidateShop($a['id'],'digital'));self::assertWPError($r->assertCandidateShop($a['id'],'goods'));}
 public function testLegacyUnassignedApprovedHistoryCannotBePromoted():void {global $wpdb;$title='Legacy '.wp_rand();$wpdb->insert(DigiForge\Database\Tables::research_candidates(),['title'=>$title,'canonical_title'=>$title,'fingerprint'=>hash('sha256',$title),'score_version'=>'v1','score_inputs'=>'{}','review_status'=>'APPROVED','created_by'=>get_current_user_id(),'created_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true)]);$id=(int)$wpdb->insert_id;$r=(new DigiForge\Research\Repository())->promote($id);self::assertWPError($r);self::assertSame('digiforge_research_scope_required',$r->get_error_code());self::assertSame('{}',$wpdb->get_var($wpdb->prepare('SELECT score_inputs FROM '.DigiForge\Database\Tables::research_candidates().' WHERE id=%d',$id)));}
 public function testRestIdempotencyIsIndependentAcrossExplicitShops():void {$controller=new DigiForge\REST\ResearchController();$responses=[];foreach(['digital','personalized_pod'] as $shop){$request=new WP_REST_Request('POST','/digiforge/v1/research/sources');$request->set_header('Content-Type','application/json');$request->set_header('Idempotency-Key','scope-key-'.get_current_user_id());$request->set_body(wp_json_encode(['shop_key'=>$shop,'name'=>'Same manual source']));$response=$controller->createSource($request);self::assertInstanceOf(WP_REST_Response::class,$response);$responses[]=$response->get_data();}self::assertNotSame($responses[0]['id'],$responses[1]['id']);}
 public function testInvalidScopeRestListReturnsAnErrorRatherThanHttp200():void {$request=new WP_REST_Request('GET','/digiforge/v1/research/candidates');$request['entity']='candidates';$request['shop_key']='invalid-shop';$r=(new DigiForge\REST\ResearchController())->list($request);self::assertWPError($r);self::assertSame(400,$r->get_error_data()['status']);}
 public function testMalformedLegacyOwnershipIsExcludedFromScopedRead():void {global $wpdb;$title='Malformed '.wp_rand();$wpdb->insert(DigiForge\Database\Tables::research_candidates(),['title'=>$title,'canonical_title'=>$title,'fingerprint'=>hash('sha256',$title),'score_version'=>'v1','score_inputs'=>'not-json','created_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true)]);$id=(int)$wpdb->insert_id;$r=(new DigiForge\Research\Repository())->list('candidates',1,100,'digital');self::assertFalse(is_wp_error($r));self::assertNotContains($id,array_column($r['items'],'id'));self::assertSame('not-json',$wpdb->get_var($wpdb->prepare('SELECT score_inputs FROM '.DigiForge\Database\Tables::research_candidates().' WHERE id=%d',$id)));}
}
