<?php
declare(strict_types=1);
final class Schema19LifecycleProvenanceTest extends WP_UnitTestCase{
 protected function setUp():void{parent::setUp();DigiForge\Core\Activator::activate();wp_set_current_user(self::factory()->user->create(['role'=>'administrator']));}
 private function package(string $seed):array{global $wpdb;$ph=hash('sha256',$seed);$now=current_time('mysql',true);$wpdb->insert(DigiForge\Database\Tables::pod_authorization_packages(),['order_id'=>1,'render_evidence_id'=>1,'provider_mapping_id'=>1,'ownership_mapping_id'=>1,'readiness_hash'=>hash('sha256',$seed.'-ready'),'package_hash'=>$ph,'state'=>'APPROVED_PACKAGE','approved_by'=>get_current_user_id(),'approved_at'=>$now,'external_execution_authorized'=>0,'external_execution_performed'=>0,'created_at'=>$now]);return [(int)$wpdb->insert_id,$ph];}
 public function testSchema19CreatesProvenanceAndExplicitClosureState():void{global $wpdb;self::assertSame(DigiForge\Database\MigrationPlan::LATEST,(int)get_option('digiforge_db_schema_version'));self::assertSame(DigiForge\Database\Tables::pod_authorization_bindings(),$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',DigiForge\Database\Tables::pod_authorization_bindings())));$columns=$wpdb->get_col('DESC '.DigiForge\Database\Tables::pod_lifecycle_closures(),0);self::assertContains('external_execution_state',$columns);}
 public function testHistoryUsesProspectiveBindingBeforeClosure():void{global $wpdb;$now=current_time('mysql',true);$auth=hash('sha256','v19-history-auth');$nonce='v19_history_nonce_123456789012345';$nh=hash('sha256',$nonce);$ph=hash('sha256','v19-history-package');$wpdb->insert(DigiForge\Database\Tables::pod_authorization_packages(),['order_id'=>1,'render_evidence_id'=>1,'provider_mapping_id'=>1,'ownership_mapping_id'=>1,'readiness_hash'=>hash('sha256','v19-ready'),'package_hash'=>$ph,'state'=>'APPROVED_PACKAGE','approved_by'=>get_current_user_id(),'approved_at'=>$now,'external_execution_authorized'=>0,'external_execution_performed'=>0,'created_at'=>$now]);$pid=(int)$wpdb->insert_id;self::assertTrue(DigiForge\POD\ExecutionNonceLedger::consume($nonce,$auth,get_current_user_id()));$wpdb->insert(DigiForge\Database\Tables::pod_authorization_bindings(),['package_id'=>$pid,'package_hash'=>$ph,'authorization_hash'=>$auth,'nonce_hash'=>$nh,'bound_by'=>get_current_user_id(),'bound_at'=>$now]);$h=(new DigiForge\POD\ProductionLifecycleHistoryReadModel())->project($auth);self::assertSame('CONSUMED_AWAITING_OUTCOME',$h['lifecycle_state']);self::assertSame($pid,(int)$h['authorization_package']['id']);self::assertSame($auth,$h['authorization_binding']['authorization_hash']);self::assertSame('BOUND',$h['provenance_state']);}
 public function testClosureRejectsConflictingProspectiveProvenance():void{global $wpdb;$now=current_time('mysql',true);$auth=hash('sha256','v19-conflict-auth');$nonce='v19_conflict_nonce_12345678901234';$nh=hash('sha256',$nonce);$ph=hash('sha256','v19-package-a');$wpdb->insert(DigiForge\Database\Tables::pod_authorization_packages(),['order_id'=>1,'render_evidence_id'=>1,'provider_mapping_id'=>1,'ownership_mapping_id'=>1,'readiness_hash'=>hash('sha256','v19-r'),'package_hash'=>$ph,'state'=>'APPROVED_PACKAGE','approved_by'=>get_current_user_id(),'approved_at'=>$now,'external_execution_authorized'=>0,'external_execution_performed'=>0,'created_at'=>$now]);$pid=(int)$wpdb->insert_id;self::assertTrue(DigiForge\POD\ExecutionNonceLedger::consume($nonce,$auth,get_current_user_id()));$wpdb->insert(DigiForge\Database\Tables::pod_authorization_bindings(),['package_id'=>$pid+999,'package_hash'=>hash('sha256','wrong'),'authorization_hash'=>$auth,'nonce_hash'=>$nh,'bound_by'=>get_current_user_id(),'bound_at'=>$now]);$fh=hash('sha256','v19-f');$wpdb->insert(DigiForge\Database\Tables::pod_execution_failures(),['action'=>'X','evidence_hash'=>hash('sha256','v19-e'),'authorization_hash'=>$auth,'nonce_hash'=>$nh,'failure_category'=>'adapter_error','failure_code'=>'timeout','executed_by'=>get_current_user_id(),'recorded_at'=>$now,'failure_hash'=>$fh,'created_at'=>$now]);$projection=(new DigiForge\POD\ConsumedPermitOutcomeReadModel())->project($auth);$closure=(new DigiForge\POD\ProductionLifecycleClosure())->close(['id'=>$pid,'package_hash'=>$ph,'state'=>'APPROVED_PACKAGE','approved_by'=>get_current_user_id()],$projection,get_current_user_id());$saved=DigiForge\POD\ProductionLifecycleClosureRepository::save($closure);self::assertWPError($saved);self::assertSame('production_closure_provenance_conflict',$saved->get_error_code());}
 public function testAtomicConsumptionPersistsNonceAndBindingTogether():void{global $wpdb;$auth=hash('sha256','atomic-auth');$nonce='atomic_nonce_12345678901234567890';[$pid,$ph]=$this->package('atomic-package');$saved=DigiForge\POD\ProductionExecutionConsumptionRepository::consume($nonce,$auth,$pid,$ph,get_current_user_id());self::assertFalse(is_wp_error($saved));self::assertSame($auth,$wpdb->get_var($wpdb->prepare('SELECT authorization_hash FROM '.DigiForge\Database\Tables::pod_execution_nonces().' WHERE nonce_hash=%s',hash('sha256',$nonce))));$binding=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.DigiForge\Database\Tables::pod_authorization_bindings().' WHERE authorization_hash=%s',$auth),ARRAY_A);self::assertSame($pid,(int)$binding['package_id']);self::assertSame($ph,$binding['package_hash']);$replay=DigiForge\POD\ProductionExecutionConsumptionRepository::consume($nonce,$auth,$pid,$ph,get_current_user_id());self::assertWPError($replay);self::assertSame('digiforge_execution_replay',$replay->get_error_code());}
 public function testBindingFailureRollsBackNonceConsumption():void{global $wpdb;$auth=hash('sha256','rollback-auth');$nonce='rollback_nonce_123456789012345678';[$pid,$ph]=$this->package('rollback-package');$wpdb->insert(DigiForge\Database\Tables::pod_authorization_bindings(),['package_id'=>$pid,'package_hash'=>hash('sha256','existing'),'authorization_hash'=>$auth,'nonce_hash'=>hash('sha256','other_nonce_12345678901234567890'),'bound_by'=>get_current_user_id(),'bound_at'=>current_time('mysql',true)]);$saved=DigiForge\POD\ProductionExecutionConsumptionRepository::consume($nonce,$auth,$pid,$ph,get_current_user_id());self::assertWPError($saved);self::assertSame('production_permit_package_binding_conflict',$saved->get_error_code());self::assertNull($wpdb->get_var($wpdb->prepare('SELECT authorization_hash FROM '.DigiForge\Database\Tables::pod_execution_nonces().' WHERE nonce_hash=%s',hash('sha256',$nonce))));}
 public function testHistoryRejectsBindingPackageHashMismatch():void{global $wpdb;$now=current_time('mysql',true);$auth=hash('sha256','history-hash-conflict');$ph=hash('sha256','actual-package');$wpdb->insert(DigiForge\Database\Tables::pod_authorization_packages(),['order_id'=>1,'render_evidence_id'=>1,'provider_mapping_id'=>1,'ownership_mapping_id'=>1,'readiness_hash'=>hash('sha256','r'),'package_hash'=>$ph,'state'=>'APPROVED_PACKAGE','approved_by'=>get_current_user_id(),'approved_at'=>$now,'external_execution_authorized'=>0,'external_execution_performed'=>0,'created_at'=>$now]);$pid=(int)$wpdb->insert_id;$wpdb->insert(DigiForge\Database\Tables::pod_authorization_bindings(),['package_id'=>$pid,'package_hash'=>hash('sha256','wrong-package'),'authorization_hash'=>$auth,'nonce_hash'=>hash('sha256','history_nonce_123456789012345678'),'bound_by'=>get_current_user_id(),'bound_at'=>$now]);$h=(new DigiForge\POD\ProductionLifecycleHistoryReadModel())->project($auth);self::assertWPError($h);self::assertSame('production_history_provenance_conflict',$h->get_error_code());}

 public function testV18MigrationBackfillsOnlyKnownTerminalClosureStates():void{global $wpdb;$table=DigiForge\Database\Tables::pod_lifecycle_closures();$now=current_time('mysql',true);$wpdb->query("ALTER TABLE $table DROP COLUMN external_execution_state");update_option('digiforge_db_schema_version',18,false);update_option('digiforge_db_version','18',false);foreach([['EXECUTION_SUCCEEDED','s'],['EXECUTION_FAILED','f']] as [$state,$key]){$wpdb->insert($table,['package_id'=>$key==='s'?9101:9102,'package_hash'=>hash('sha256','pkg-'.$key),'authorization_hash'=>hash('sha256','auth-'.$key),'outcome_state'=>$state,'closure_hash'=>hash('sha256','closure-'.$key),'closed_by'=>get_current_user_id(),'external_execution_performed'=>$state==='EXECUTION_SUCCEEDED'?1:0,'created_at'=>$now]);}self::assertTrue(DigiForge\Database\V6OperationalSchema::migrateIfNeeded());self::assertTrue(DigiForge\Database\ScopedPolicySchema::migrateIfNeeded());self::assertSame(23,(int)get_option('digiforge_db_schema_version'));self::assertSame('23',(string)get_option('digiforge_db_version'));self::assertSame('CONFIRMED_SUCCESS',$wpdb->get_var($wpdb->prepare("SELECT external_execution_state FROM $table WHERE package_id=%d",9101)));self::assertSame('CONFIRMED_FAILURE',$wpdb->get_var($wpdb->prepare("SELECT external_execution_state FROM $table WHERE package_id=%d",9102)));self::assertSame(0,(int)$wpdb->get_var('SELECT COUNT(*) FROM '.DigiForge\Database\Tables::pod_authorization_bindings()." WHERE package_id IN (9101,9102)"));}

 public function testHistoryRejectsClosurePackageHashDrift():void{global $wpdb;$now=current_time('mysql',true);$auth=hash('sha256','closure-drift-auth');$ph=hash('sha256','closure-drift-package');$wpdb->insert(DigiForge\Database\Tables::pod_authorization_packages(),['order_id'=>1,'render_evidence_id'=>1,'provider_mapping_id'=>1,'ownership_mapping_id'=>1,'readiness_hash'=>hash('sha256','closure-ready'),'package_hash'=>$ph,'state'=>'APPROVED_PACKAGE','approved_by'=>get_current_user_id(),'approved_at'=>$now,'external_execution_authorized'=>0,'external_execution_performed'=>0,'created_at'=>$now]);$pid=(int)$wpdb->insert_id;$nonce='closure_drift_nonce_12345678901234';self::assertTrue(DigiForge\POD\ExecutionNonceLedger::consume($nonce,$auth,get_current_user_id()));$fh=hash('sha256','closure-drift-failure');$wpdb->insert(DigiForge\Database\Tables::pod_execution_failures(),['action'=>'X','evidence_hash'=>hash('sha256','closure-e'),'authorization_hash'=>$auth,'nonce_hash'=>hash('sha256',$nonce),'failure_category'=>'adapter_error','failure_code'=>'timeout','executed_by'=>get_current_user_id(),'recorded_at'=>$now,'failure_hash'=>$fh,'created_at'=>$now]);$wpdb->insert(DigiForge\Database\Tables::pod_execution_outcomes(),['authorization_hash'=>$auth,'outcome_type'=>'FAILED','outcome_hash'=>$fh,'created_at'=>$now]);$wpdb->insert(DigiForge\Database\Tables::pod_lifecycle_closures(),['package_id'=>$pid,'package_hash'=>hash('sha256','wrong-closure-package'),'authorization_hash'=>$auth,'outcome_state'=>'EXECUTION_FAILED','closure_hash'=>hash('sha256','closure-drift'),'closed_by'=>get_current_user_id(),'external_execution_performed'=>0,'external_execution_state'=>'CONFIRMED_FAILURE','created_at'=>$now]);$h=(new DigiForge\POD\ProductionLifecycleHistoryReadModel())->project($auth);self::assertWPError($h);self::assertSame('production_history_closure_provenance_conflict',$h->get_error_code());}
 public function testAttentionSurfacesLegacyUnboundAndProvenanceIntegrity():void{global $wpdb;$now=current_time('mysql',true);$auth=hash('sha256','legacy-unbound-attention');$wpdb->insert(DigiForge\Database\Tables::pod_execution_nonces(),['nonce_hash'=>hash('sha256','legacy-attention-nonce'),'authorization_hash'=>$auth,'consumed_by'=>get_current_user_id(),'consumed_at'=>$now]);$badAuth=hash('sha256','bad-provenance-attention');$wpdb->insert(DigiForge\Database\Tables::pod_authorization_bindings(),['package_id'=>999999,'package_hash'=>hash('sha256','missing-package'),'authorization_hash'=>$badAuth,'nonce_hash'=>hash('sha256','bad-provenance-nonce'),'bound_by'=>get_current_user_id(),'bound_at'=>$now]);$s=(new DigiForge\Portal\AttentionReadModel())->summary();self::assertGreaterThanOrEqual(1,$s['production_legacy_unbound']);self::assertGreaterThanOrEqual(1,$s['production_provenance_integrity']);self::assertSame('READ_ONLY_NO_EXECUTION',$s['external_execution_state']);}

 public function testAtomicConsumptionTablesUseTransactionalEngine():void{global $wpdb;foreach([DigiForge\Database\Tables::pod_execution_nonces(),DigiForge\Database\Tables::pod_authorization_bindings()] as $table){$engine=$wpdb->get_var($wpdb->prepare('SELECT ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s',$table));self::assertSame('INNODB',strtoupper((string)$engine));}}
 public function testProvenanceIntegrityDrillDownIsReadOnlyAndBounded():void{$x=(new DigiForge\POD\ProductionProvenanceIntegrityReadModel())->recent(500);self::assertTrue($x['read_only']);self::assertFalse($x['retry_permitted']);self::assertFalse($x['external_execution_authorized']);self::assertLessThanOrEqual(200,$x['count']);foreach($x['items'] as $item){self::assertIsArray($item);self::assertContains($item['type'],['BINDING_PACKAGE_MISMATCH','CLOSURE_PACKAGE_MISMATCH','BINDING_CLOSURE_MISMATCH','LEGACY_UNBOUND']);self::assertContains($item['operator_state'],['OPEN','ACKNOWLEDGED','HISTORICAL']);self::assertFalse($item['retry_permitted']);self::assertFalse($item['external_execution_authorized']);}}

 public function testCompetingAuthorizationForSamePackageRollsBackLosingNonce():void{global $wpdb;[$pid,$ph]=$this->package('race-package');$authA=hash('sha256','race-auth-a');$authB=hash('sha256','race-auth-b');$nonceA='race_nonce_a_12345678901234567890';$nonceB='race_nonce_b_12345678901234567890';$first=DigiForge\POD\ProductionExecutionConsumptionRepository::consume($nonceA,$authA,$pid,$ph,get_current_user_id());self::assertFalse(is_wp_error($first));$second=DigiForge\POD\ProductionExecutionConsumptionRepository::consume($nonceB,$authA,$pid,$ph,get_current_user_id());self::assertWPError($second);self::assertSame('production_permit_package_binding_conflict',$second->get_error_code());self::assertNull($wpdb->get_var($wpdb->prepare('SELECT authorization_hash FROM '.DigiForge\Database\Tables::pod_execution_nonces().' WHERE nonce_hash=%s',hash('sha256',$nonceB))));self::assertSame($authA,$wpdb->get_var($wpdb->prepare('SELECT authorization_hash FROM '.DigiForge\Database\Tables::pod_execution_nonces().' WHERE nonce_hash=%s',hash('sha256',$nonceA))));}
 public function testIntegrityDrillDownCorrelatesDurableOutcomeEvidence():void{global $wpdb;$now=current_time('mysql',true);$auth=hash('sha256','integrity-correlation-auth');$out=hash('sha256','integrity-correlation-outcome');$wpdb->insert(DigiForge\Database\Tables::pod_execution_nonces(),['nonce_hash'=>hash('sha256','integrity-correlation-nonce'),'authorization_hash'=>$auth,'consumed_by'=>get_current_user_id(),'consumed_at'=>$now]);$wpdb->insert(DigiForge\Database\Tables::pod_execution_outcomes(),['authorization_hash'=>$auth,'outcome_type'=>'FAILED','outcome_hash'=>$out,'created_at'=>$now]);$x=(new DigiForge\POD\ProductionProvenanceIntegrityReadModel())->recent(200);$match=null;foreach($x['items'] as $item)if($item['authorization_hash']===$auth){$match=$item;break;}self::assertIsArray($match);self::assertSame('LEGACY_UNBOUND',$match['type']);self::assertSame($out,$match['outcome']['outcome_hash']);self::assertMatchesRegularExpression('/^[a-f0-9]{64}$/',$match['correlation_hash']);self::assertFalse($x['retry_permitted']);self::assertFalse($x['external_execution_authorized']);}

 public function testSchema20PersistsIntegrityAcknowledgementWithoutExecutionAuthority():void{global $wpdb;self::assertSame(DigiForge\Database\MigrationPlan::LATEST,(int)get_option('digiforge_db_schema_version'));self::assertSame(DigiForge\Database\Tables::pod_provenance_integrity_acknowledgements(),$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',DigiForge\Database\Tables::pod_provenance_integrity_acknowledgements())));$now=current_time('mysql',true);$auth=hash('sha256','integrity-ack-auth');$wpdb->insert(DigiForge\Database\Tables::pod_execution_nonces(),['nonce_hash'=>hash('sha256','integrity-ack-nonce'),'authorization_hash'=>$auth,'consumed_by'=>get_current_user_id(),'consumed_at'=>$now]);$x=(new DigiForge\POD\ProductionProvenanceIntegrityReadModel())->recent(200);$item=null;foreach($x['items'] as $candidate)if($candidate['authorization_hash']===$auth){$item=$candidate;break;}self::assertIsArray($item);$saved=DigiForge\POD\ProductionProvenanceIntegrityAcknowledgementRepository::acknowledge($item['correlation_hash'],$auth,$item['type'],get_current_user_id());self::assertFalse(is_wp_error($saved));self::assertFalse($saved['retry_permitted']);self::assertFalse($saved['external_execution_authorized']);$again=DigiForge\POD\ProductionProvenanceIntegrityAcknowledgementRepository::acknowledge($item['correlation_hash'],$auth,$item['type'],get_current_user_id());self::assertSame((int)$saved['id'],(int)$again['id']);}

 public function testIntegrityAcknowledgementProjectsAcknowledgedWithoutReactivation():void{global $wpdb;$now=current_time('mysql',true);$auth=hash('sha256','ack-projection-auth');$nonce='ack_projection_nonce_123456789012345';$wpdb->insert(DigiForge\Database\Tables::pod_execution_nonces(),['nonce_hash'=>hash('sha256',$nonce),'authorization_hash'=>$auth,'consumed_by'=>get_current_user_id(),'consumed_at'=>$now]);$before=(new DigiForge\POD\ProductionProvenanceIntegrityReadModel())->recent(200);$item=null;foreach($before['items'] as $candidate)if($candidate['authorization_hash']===$auth){$item=$candidate;break;}self::assertIsArray($item);self::assertSame('OPEN',$item['operator_state']);$saved=DigiForge\POD\ProductionProvenanceIntegrityAcknowledgementRepository::acknowledge($item['correlation_hash'],$auth,$item['type'],get_current_user_id());self::assertFalse(is_wp_error($saved));$after=(new DigiForge\POD\ProductionProvenanceIntegrityReadModel())->recent(200);$seen=null;foreach($after['items'] as $candidate)if($candidate['authorization_hash']===$auth){$seen=$candidate;break;}self::assertSame('ACKNOWLEDGED',$seen['operator_state']);self::assertFalse($seen['retry_permitted']);self::assertFalse($seen['external_execution_authorized']);$replay=DigiForge\POD\ProductionExecutionConsumptionRepository::consume($nonce,$auth,777,hash('sha256','never-reactivate'),get_current_user_id());self::assertWPError($replay);self::assertSame('digiforge_execution_replay',$replay->get_error_code());}
 public function testIntegrityAcknowledgementConflictsForDifferentReviewer():void{global $wpdb;$now=current_time('mysql',true);$auth=hash('sha256','ack-conflict-auth');$wpdb->insert(DigiForge\Database\Tables::pod_execution_nonces(),['nonce_hash'=>hash('sha256','ack-conflict-nonce'),'authorization_hash'=>$auth,'consumed_by'=>get_current_user_id(),'consumed_at'=>$now]);$x=(new DigiForge\POD\ProductionProvenanceIntegrityReadModel())->recent(200);$item=null;foreach($x['items'] as $candidate)if($candidate['authorization_hash']===$auth){$item=$candidate;break;}$first=DigiForge\POD\ProductionProvenanceIntegrityAcknowledgementRepository::acknowledge($item['correlation_hash'],$auth,$item['type'],get_current_user_id());self::assertFalse(is_wp_error($first));$other=self::factory()->user->create(['role'=>'administrator']);$second=DigiForge\POD\ProductionProvenanceIntegrityAcknowledgementRepository::acknowledge($item['correlation_hash'],$auth,$item['type'],$other);self::assertWPError($second);self::assertSame('production_integrity_ack_conflict',$second->get_error_code());}

 public function testConsumptionRejectsPackageIdHashDriftBeforeNonceMutation():void{global $wpdb;[$pid,$ph]=$this->package('boundary-package');$auth=hash('sha256','boundary-auth');$nonce='boundary_nonce_12345678901234567890';$bad=DigiForge\POD\ProductionExecutionConsumptionRepository::consume($nonce,$auth,$pid,hash('sha256','wrong-boundary-package'),get_current_user_id());self::assertWPError($bad);self::assertSame('production_permit_package_provenance_mismatch',$bad->get_error_code());self::assertFalse($bad->get_error_data()['retry_permitted']);self::assertFalse($bad->get_error_data()['external_execution_authorized']);self::assertNull($wpdb->get_var($wpdb->prepare('SELECT authorization_hash FROM '.DigiForge\Database\Tables::pod_execution_nonces().' WHERE nonce_hash=%s',hash('sha256',$nonce))));}

 public function testSchema21HistoricalIntegrityEvidenceSurvivesRepairWithoutReactivation():void{
  global $wpdb;self::assertSame(DigiForge\Database\Tables::pod_provenance_integrity_evidence(),$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',DigiForge\Database\Tables::pod_provenance_integrity_evidence())));
  [$pid,$ph]=$this->package('historical-repair-package');$auth=hash('sha256','historical-repair-auth');$nonce='historical_repair_nonce_1234567890123';$nh=hash('sha256',$nonce);$now=current_time('mysql',true);
  $wpdb->insert(DigiForge\Database\Tables::pod_execution_nonces(),['nonce_hash'=>$nh,'authorization_hash'=>$auth,'consumed_by'=>get_current_user_id(),'consumed_at'=>$now]);
  $wrong=hash('sha256','historical-wrong-package');$wpdb->insert(DigiForge\Database\Tables::pod_authorization_bindings(),['package_id'=>$pid,'package_hash'=>$wrong,'authorization_hash'=>$auth,'nonce_hash'=>$nh,'bound_by'=>get_current_user_id(),'bound_at'=>$now]);
  $before=(new DigiForge\POD\ProductionProvenanceIntegrityReadModel())->recent(200);$item=null;foreach($before['items'] as $candidate)if(($candidate['authorization_hash']??'')===$auth&&($candidate['type']??'')==='BINDING_PACKAGE_MISMATCH'){$item=$candidate;break;}self::assertIsArray($item);self::assertFalse($item['historical_evidence']);
  $ack=DigiForge\POD\ProductionProvenanceIntegrityAcknowledgementRepository::acknowledge($item['correlation_hash'],$auth,$item['type'],get_current_user_id());self::assertFalse(is_wp_error($ack));self::assertFalse($ack['retry_permitted']);self::assertFalse($ack['external_execution_authorized']);
  $wpdb->update(DigiForge\Database\Tables::pod_authorization_bindings(),['package_hash'=>$ph],['authorization_hash'=>$auth]);
  $after=(new DigiForge\POD\ProductionProvenanceIntegrityReadModel())->recent(200);$historical=null;foreach($after['items'] as $candidate)if(($candidate['correlation_hash']??'')===$item['correlation_hash']){$historical=$candidate;break;}self::assertIsArray($historical);self::assertTrue($historical['historical_evidence']);self::assertSame('ACKNOWLEDGED',$historical['operator_state']);self::assertFalse($historical['retry_permitted']);self::assertFalse($historical['external_execution_authorized']);
  self::assertSame($auth,$wpdb->get_var($wpdb->prepare('SELECT authorization_hash FROM '.DigiForge\Database\Tables::pod_execution_nonces().' WHERE nonce_hash=%s',$nh)));self::assertSame('0',(string)$wpdb->get_var($wpdb->prepare('SELECT external_execution_authorized FROM '.DigiForge\Database\Tables::pod_authorization_packages().' WHERE id=%d',$pid)));
  $replay=DigiForge\POD\ProductionExecutionConsumptionRepository::consume($nonce,$auth,$pid,$ph,get_current_user_id());self::assertWPError($replay);self::assertSame('digiforge_execution_replay',$replay->get_error_code());self::assertFalse($replay->get_error_data()['retry_permitted']);self::assertFalse($replay->get_error_data()['external_execution_authorized']);
 }

 public function testPermitPersistenceReconciliationIsReadOnlyAndNeverRestoresAuthority():void{
  global $wpdb;[$pid,$ph]=$this->package('persistence-reconcile-package');$auth=hash('sha256','persistence-reconcile-auth');$nonce='persistence_reconcile_nonce_123456789';$nh=hash('sha256',$nonce);
  $unknown=(new DigiForge\POD\ProductionPermitPersistenceReadModel())->project($nh,$auth,$pid,$ph);self::assertSame('UNKNOWN',$unknown['persistence_state']);self::assertFalse($unknown['nonce_consumed']);self::assertFalse($unknown['retry_permitted']);self::assertFalse($unknown['external_execution_authorized']);self::assertTrue($unknown['read_only']);
  $saved=DigiForge\POD\ProductionExecutionConsumptionRepository::consume($nonce,$auth,$pid,$ph,get_current_user_id());self::assertFalse(is_wp_error($saved));
  $observed=(new DigiForge\POD\ProductionPermitPersistenceReadModel())->project($nh,$auth,$pid,$ph);self::assertSame('PERSISTED_OBSERVED',$observed['persistence_state']);self::assertTrue($observed['nonce_consumed']);self::assertFalse($observed['retry_permitted']);self::assertFalse($observed['external_execution_authorized']);self::assertSame('0',(string)$wpdb->get_var($wpdb->prepare('SELECT external_execution_authorized FROM '.DigiForge\Database\Tables::pod_authorization_packages().' WHERE id=%d',$pid)));
  $replay=DigiForge\POD\ProductionExecutionConsumptionRepository::consume($nonce,$auth,$pid,$ph,get_current_user_id());self::assertWPError($replay);self::assertSame('digiforge_execution_replay',$replay->get_error_code());
 }

 public function testPermitPersistenceObservationTransitionsWithoutGrantingRetryOrAuthority():void{
  global $wpdb;[$pid,$ph]=$this->package('persistence-observation-package');$auth=hash('sha256','persistence-observation-auth');$nonce='persistence_observation_nonce_1234567';$nh=hash('sha256',$nonce);
  $unknown=(new DigiForge\POD\ProductionPermitPersistenceReadModel())->project($nh,$auth,$pid,$ph);DigiForge\POD\ProductionPermitPersistenceObservationRepository::observe($nh,$auth,$pid,$ph,$unknown);$s=DigiForge\POD\ProductionPermitPersistenceObservationRepository::summary();self::assertGreaterThanOrEqual(1,$s['unknown_count']);self::assertFalse($s['retry_permitted']);self::assertFalse($s['external_execution_authorized']);
  $saved=DigiForge\POD\ProductionExecutionConsumptionRepository::consume($nonce,$auth,$pid,$ph,get_current_user_id());self::assertFalse(is_wp_error($saved));$observed=(new DigiForge\POD\ProductionPermitPersistenceReadModel())->project($nh,$auth,$pid,$ph);DigiForge\POD\ProductionPermitPersistenceObservationRepository::observe($nh,$auth,$pid,$ph,$observed);
  $row=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.DigiForge\Database\Tables::pod_permit_persistence_observations().' WHERE authorization_hash=%s',$auth),ARRAY_A);self::assertSame('PERSISTED_OBSERVED',$row['persistence_state']);self::assertSame('0',(string)$wpdb->get_var($wpdb->prepare('SELECT external_execution_authorized FROM '.DigiForge\Database\Tables::pod_authorization_packages().' WHERE id=%d',$pid)));
  $attention=(new DigiForge\Portal\AttentionReadModel())->summary();self::assertGreaterThanOrEqual(1,$attention['production_permit_persistence_observed']);self::assertSame('READ_ONLY_NO_EXECUTION',$attention['external_execution_state']);
 }
 public function testAttentionSeparatesHistoricalIntegrityFromCurrentOpenAttention():void{
  global $wpdb;[$pid,$ph]=$this->package('attention-history-package');$auth=hash('sha256','attention-history-auth');$now=current_time('mysql',true);$wpdb->insert(DigiForge\Database\Tables::pod_authorization_bindings(),['package_id'=>$pid,'package_hash'=>hash('sha256','attention-history-wrong'),'authorization_hash'=>$auth,'nonce_hash'=>hash('sha256','attention-history-nonce'),'bound_by'=>get_current_user_id(),'bound_at'=>$now]);
  $first=(new DigiForge\POD\ProductionProvenanceIntegrityReadModel())->recent(200);$match=null;foreach($first['items'] as $candidate)if(($candidate['authorization_hash']??'')===$auth){$match=$candidate;break;}self::assertIsArray($match);$wpdb->update(DigiForge\Database\Tables::pod_authorization_bindings(),['package_hash'=>$ph],['authorization_hash'=>$auth]);
  $attention=(new DigiForge\Portal\AttentionReadModel())->summary();self::assertGreaterThanOrEqual(1,$attention['production_provenance_integrity_historical']);self::assertFalse($attention['production_provenance_integrity_projection']['retry_permitted']);self::assertFalse($attention['production_provenance_integrity_projection']['external_execution_authorized']);
 }

 public function testAcknowledgementInsertRaceAcceptsIdenticalWinnerAndRejectsDivergentWinner():void{
  global $wpdb;$now=current_time('mysql',true);$auth=hash('sha256','ack-race-auth');$wpdb->insert(DigiForge\Database\Tables::pod_execution_nonces(),['nonce_hash'=>hash('sha256','ack-race-nonce'),'authorization_hash'=>$auth,'consumed_by'=>get_current_user_id(),'consumed_at'=>$now]);$x=(new DigiForge\POD\ProductionProvenanceIntegrityReadModel())->recent(200);$item=null;foreach($x['items'] as $candidate)if(($candidate['authorization_hash']??'')===$auth){$item=$candidate;break;}self::assertIsArray($item);$reviewer=get_current_user_id();
  DigiForge\POD\ProductionProvenanceIntegrityAcknowledgementRepository::setBeforeInsertHookForTest(function(array $row)use($wpdb):void{$wpdb->insert(DigiForge\Database\Tables::pod_provenance_integrity_acknowledgements(),$row);});
  $same=DigiForge\POD\ProductionProvenanceIntegrityAcknowledgementRepository::acknowledge($item['correlation_hash'],$auth,$item['type'],$reviewer);self::assertFalse(is_wp_error($same));self::assertFalse($same['retry_permitted']);self::assertFalse($same['external_execution_authorized']);
  $auth2=hash('sha256','ack-race-conflict-auth');$wpdb->insert(DigiForge\Database\Tables::pod_execution_nonces(),['nonce_hash'=>hash('sha256','ack-race-conflict-nonce'),'authorization_hash'=>$auth2,'consumed_by'=>$reviewer,'consumed_at'=>$now]);$y=(new DigiForge\POD\ProductionProvenanceIntegrityReadModel())->recent(200);$item2=null;foreach($y['items'] as $candidate)if(($candidate['authorization_hash']??'')===$auth2){$item2=$candidate;break;}self::assertIsArray($item2);
  DigiForge\POD\ProductionProvenanceIntegrityAcknowledgementRepository::setBeforeInsertHookForTest(function(array $row)use($wpdb):void{$row['reviewed_by']=(int)$row['reviewed_by']+1000;$row['acknowledgement_hash']=hash('sha256','divergent-race-winner');$wpdb->insert(DigiForge\Database\Tables::pod_provenance_integrity_acknowledgements(),$row);});
  $different=DigiForge\POD\ProductionProvenanceIntegrityAcknowledgementRepository::acknowledge($item2['correlation_hash'],$auth2,$item2['type'],$reviewer);self::assertWPError($different);self::assertSame('production_integrity_ack_conflict',$different->get_error_code());
 }
 public function testPersistenceDrilldownIsBoundedReadOnlyAndNonAuthorizing():void{
  global $wpdb;[$pid,$ph]=$this->package('drilldown-package');$auth=hash('sha256','drilldown-auth');$nh=hash('sha256','drilldown-nonce');$projection=(new DigiForge\POD\ProductionPermitPersistenceReadModel())->project($nh,$auth,$pid,$ph);DigiForge\POD\ProductionPermitPersistenceObservationRepository::observe($nh,$auth,$pid,$ph,$projection);$x=DigiForge\POD\ProductionPermitPersistenceObservationRepository::recent(500);self::assertLessThanOrEqual(200,$x['count']);self::assertTrue($x['read_only']);self::assertFalse($x['retry_permitted']);self::assertFalse($x['external_execution_authorized']);foreach($x['items'] as $item){self::assertContains($item['persistence_state'],['UNKNOWN','PERSISTED_OBSERVED']);self::assertFalse($item['retry_permitted']);self::assertFalse($item['external_execution_authorized']);}
 }
}
