<?php
declare(strict_types=1);
use DigiForge\POD\ProductionTemplateRepository;
use DigiForge\AI\ShopAiGovernanceRepository;
final class TemplateCycleCapTest extends WP_UnitTestCase {
 private string $shop;
 public function setUp():void {parent::setUp();DigiForge\Core\Activator::activate();$this->shop='cap-'.wp_rand();$this->policy($this->shop);}
 private function policy(string $shop):void {$r=(new ShopAiGovernanceRepository())->savePolicy(['shop_key'=>$shop,'currency'=>'USD','template_cap'=>['limit'=>8,'duration_seconds'=>604800,'anchor_utc'=>'2026-01-05 00:00:00']]);self::assertFalse(is_wp_error($r));}
 private function input(int $n,string $shop=''):array {return ['shop_key'=>$shop?:$this->shop,'template_id'=>$this->shop.'-'.$n,'template_version'=>1,'supplier'=>'printify','provider_blueprint_id'=>1,'provider_id'=>2,'variant_ids'=>[3],'print_areas'=>[['position'=>'front','decoration_method'=>'dtg','width_px'=>100,'height_px'=>100]],'personalization_pipeline'=>'DIGIFORGE_RENDER','personalization_engine'=>'PHOTO_TEXT'];}
 public function testNewCandidateRequiresExplicitShop():void {$a=$this->input(1);unset($a['shop_key']);$r=(new ProductionTemplateRepository())->save($a);self::assertTrue(is_wp_error($r));self::assertSame('template_cycle_scope_required',$r->get_error_code());}
 public function testEightCandidatesAllowedNinthDeniedReplayDoesNotConsume():void {$repo=new ProductionTemplateRepository();$first=null;for($i=1;$i<=8;$i++){$r=$repo->save($this->input($i));self::assertFalse(is_wp_error($r));$first??=$r;}$replay=$repo->save($this->input(1));self::assertFalse(is_wp_error($replay));self::assertTrue($replay['idempotent']);$ninth=$repo->save($this->input(9));self::assertTrue(is_wp_error($ninth));self::assertSame('template_cycle_limit_reached',$ninth->get_error_code());global $wpdb;self::assertSame('8',$wpdb->get_var($wpdb->prepare('SELECT SUM(quantity) FROM '.DigiForge\Database\Tables::shop_ai_usage().' WHERE shop_key=%s AND stage=%s',$this->shop,'template_prepare')));}
 public function testAnotherShopHasIndependentCapacity():void {$repo=new ProductionTemplateRepository();for($i=1;$i<=8;$i++)self::assertFalse(is_wp_error($repo->save($this->input($i))));$other='other-'.wp_rand();$this->policy($other);self::assertFalse(is_wp_error($repo->save($this->input(9,$other))));}
 public function testConcurrentShopLockBlocksThenFreshCheckDeniesFinalSlot():void {$repo=new ProductionTemplateRepository();for($i=1;$i<=7;$i++)self::assertFalse(is_wp_error($repo->save($this->input($i))));$other=new wpdb(DB_USER,DB_PASSWORD,DB_NAME,DB_HOST);$lock=ShopAiGovernanceRepository::generationLockName($this->shop);self::assertSame('1',$other->get_var($other->prepare('SELECT GET_LOCK(%s,0)',$lock)));try{$blocked=$repo->save($this->input(8));self::assertTrue(is_wp_error($blocked));self::assertSame('template_cycle_reservation_busy',$blocked->get_error_code());}finally{$other->get_var($other->prepare('SELECT RELEASE_LOCK(%s)',$lock));$other->close();}self::assertFalse(is_wp_error($repo->save($this->input(8))));$blocked=$repo->save($this->input(9));self::assertTrue(is_wp_error($blocked));self::assertSame('template_cycle_limit_reached',$blocked->get_error_code());}
 public function testMissingPolicyFailsClosed():void {$r=(new ProductionTemplateRepository())->save($this->input(1,'missing-'.wp_rand()));self::assertTrue(is_wp_error($r));self::assertSame('template_cycle_policy_required',$r->get_error_code());}
 public function testReplayCannotCrossShopOrOmitOwnership():void {$repo=new ProductionTemplateRepository();self::assertFalse(is_wp_error($repo->save($this->input(1))));$a=$this->input(1);$a['shop_key']='another-'.wp_rand();$r=$repo->save($a);self::assertTrue(is_wp_error($r));self::assertSame('template_cycle_owner_mismatch',$r->get_error_code());unset($a['shop_key']);$r=$repo->save($a);self::assertTrue(is_wp_error($r));self::assertSame('template_cycle_scope_required',$r->get_error_code());}
 public function testDirectNewVersionCannotTransferTemplateLineage():void {$repo=new ProductionTemplateRepository();self::assertFalse(is_wp_error($repo->save($this->input(1))));$other='transfer-'.wp_rand();$this->policy($other);$a=$this->input(1,$other);$a['template_version']=2;$r=$repo->save($a);self::assertTrue(is_wp_error($r));self::assertSame('template_cycle_owner_mismatch',$r->get_error_code());}
 public function testTemplateLineageLockExcludesDifferentVersions():void {$a=$this->input(1);$lock='digiforge-template-'.substr(hash('sha256',$a['template_id']),0,45);$other=new wpdb(DB_USER,DB_PASSWORD,DB_NAME,DB_HOST);self::assertSame('1',$other->get_var($other->prepare('SELECT GET_LOCK(%s,0)',$lock)));try{$a['template_version']=2;$r=(new ProductionTemplateRepository())->save($a);self::assertTrue(is_wp_error($r));self::assertSame('template_identity_busy',$r->get_error_code());}finally{$other->get_var($other->prepare('SELECT RELEASE_LOCK(%s)',$lock));$other->close();}}
 public function testPortalDisplaysExplicitCapacityWithoutChangingControls():void {$shop='digital';$this->policy($shop);$before=DigiForge\Core\Settings::get('stop_all',true);$old=$_GET;$_GET['df_shop']=$shop;ob_start();try{$m=new ReflectionMethod(DigiForge\Portal\Portal::class,'aiBudget');$m->invoke(new DigiForge\Portal\Portal());$html=ob_get_contents();}finally{ob_end_clean();$_GET=$old;}self::assertStringContainsString('name="template_cycle_limit" value="8"',$html);self::assertStringContainsString('name="template_cycle_anchor"',$html);self::assertStringContainsString('Current cycle used: 0',$html);self::assertSame($before,DigiForge\Core\Settings::get('stop_all',true));}
}
