<?php
declare(strict_types=1);
namespace DigiForge\AI;
use DigiForge\Database\Tables;
use WP_Error;

/** Shop-scoped AI ceilings and attributable usage evidence. */
final class ShopAiGovernanceRepository {
 public function savePolicy(array $policy,string $environment='production'):array|WP_Error{
  global $wpdb;try{$projection=ShopAiPlan::evaluate($policy);}catch(\InvalidArgumentException $e){return new WP_Error('invalid_ai_policy',$e->getMessage());}
  $shop=(string)$projection['shop_key'];$json=wp_json_encode($policy);$hash=hash('sha256',(string)$json);$now=current_time('mysql',true);
  $wpdb->last_error='';$existing=$wpdb->get_row($wpdb->prepare('SELECT id FROM '.Tables::shop_ai_policies().' WHERE shop_key=%s AND environment=%s',$shop,$environment),ARRAY_A);if(!empty($wpdb->last_error))return new WP_Error('ai_policy_evidence_unavailable','Shop AI policy evidence is unavailable.');
  $data=['currency'=>(string)$projection['currency'],'policy'=>$json,'policy_hash'=>$hash,'state'=>'ACTIVE','updated_at'=>$now];
  if(is_array($existing)){$wpdb->last_error='';$ok=$wpdb->update(Tables::shop_ai_policies(),$data,['id'=>(int)$existing['id']]);$id=(int)$existing['id'];if($ok===false||!empty($wpdb->last_error))return new WP_Error('ai_policy_persistence_failed','Shop AI policy could not be persisted.');}else{$data+=['shop_key'=>$shop,'environment'=>sanitize_key($environment),'created_by'=>get_current_user_id(),'created_at'=>$now];$wpdb->last_error='';$ok=$wpdb->insert(Tables::shop_ai_policies(),$data);$id=(int)$wpdb->insert_id;}
  if($ok===false||!empty($wpdb->last_error))return new WP_Error('ai_policy_persistence_failed','Shop AI policy could not be persisted.');
  $wpdb->last_error='';$confirmed=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Tables::shop_ai_policies().' WHERE id=%d',$id),ARRAY_A);if(!empty($wpdb->last_error)||!is_array($confirmed))return new WP_Error('ai_policy_confirmation_unavailable','Persisted shop AI policy could not be confirmed.');return $confirmed;
 }
 public function preflight(string $shop,string $stage,int $quantity,float $estimatedCost,string $environment='production',?array $runContext=null):array|WP_Error{
  $projection=$this->evaluate($shop,$environment,$runContext);if($projection instanceof WP_Error)return $projection;
  return ShopAiPlan::preflight($projection,$stage,$quantity,$estimatedCost);
 }

 public function recordUsage(array $input,?string $key=null):array|WP_Error{
  global $wpdb;$shop=sanitize_key((string)($input['shop_key']??''));$stage=sanitize_key((string)($input['stage']??''));if($shop===''||!in_array($stage,ShopAiPlan::STAGES,true))return new WP_Error('invalid_ai_usage','Valid shop_key and stage are required.');
  $runContext=$input['run_context']??null;$runId='';$runStartedAt=null;if(is_array($runContext)){$normalized=AiRunContext::normalize((string)($runContext['run_id']??''),(string)($runContext['started_at']??''));if($normalized instanceof WP_Error)return $normalized;$runId=$normalized['run_id'];$runStartedAt=$normalized['started_at'];}
  $data=['shop_key'=>$shop,'workflow'=>sanitize_key((string)($input['workflow']??'general')),'run_id'=>$runId,'run_started_at'=>$runStartedAt,'stage'=>$stage,'model_key'=>sanitize_text_field((string)($input['model_key']??'')),'product_id'=>absint($input['product_id']??0),'order_id'=>absint($input['order_id']??0),'quantity'=>max(1,(int)($input['quantity']??1)),'estimated_cost'=>max(0,(float)($input['estimated_cost']??0)),'actual_cost'=>max(0,(float)($input['actual_cost']??0)),'currency'=>strtoupper(substr(sanitize_text_field((string)($input['currency']??'USD')),0,3)),'occurred_at'=>current_time('mysql',true),'idempotency_key'=>$key===null?null:sanitize_text_field($key)];
  if($key!==null){$wpdb->last_error='';$old=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Tables::shop_ai_usage().' WHERE idempotency_key=%s',$data['idempotency_key']),ARRAY_A);if(!empty($wpdb->last_error))return new WP_Error('ai_usage_evidence_unavailable','AI usage evidence is unavailable.');if(is_array($old))return $old+['idempotent_replay'=>true];}
  $wpdb->last_error='';if($wpdb->insert(Tables::shop_ai_usage(),$data)!==1||!empty($wpdb->last_error))return new WP_Error('ai_usage_persistence_failed','AI usage evidence could not be persisted.');$wpdb->last_error='';$confirmed=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Tables::shop_ai_usage().' WHERE id=%d',(int)$wpdb->insert_id),ARRAY_A);if(!empty($wpdb->last_error)||!is_array($confirmed))return new WP_Error('ai_usage_confirmation_unavailable','Persisted AI usage evidence could not be confirmed.');return $confirmed;
 }
 public function evaluate(string $shop,string $environment='production',?array $runContext=null):array|WP_Error{
  global $wpdb;$wpdb->last_error='';$row=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Tables::shop_ai_policies().' WHERE shop_key=%s AND environment=%s AND state=%s',$shop,$environment,'ACTIVE'),ARRAY_A);if(!empty($wpdb->last_error))return new WP_Error('ai_policy_evidence_unavailable','Shop AI policy evidence is unavailable.');if(!is_array($row))return new WP_Error('ai_policy_missing','Active shop AI policy is required.');
  $policy=json_decode((string)$row['policy'],true);if(!is_array($policy))return new WP_Error('ai_policy_corrupt','Shop AI policy is invalid.');
  $now=time();$month=gmdate('Y-m-01 00:00:00',$now);$day=gmdate('Y-m-d 00:00:00',$now);$runStart=gmdate('Y-m-d H:i:s',$now);$runId='';if($runContext!==null){$normalized=AiRunContext::normalize((string)($runContext['run_id']??''),(string)($runContext['started_at']??''));if($normalized instanceof WP_Error)return $normalized;$runStart=$normalized['started_at'];$runId=$normalized['run_id'];}
  $wpdb->last_error='';$usage=$wpdb->get_results($wpdb->prepare('SELECT stage,SUM(quantity) quantity,SUM(actual_cost) cost FROM '.Tables::shop_ai_usage().' WHERE shop_key=%s AND occurred_at>=%s GROUP BY stage',$shop,$month),ARRAY_A);if(!empty($wpdb->last_error)||!is_array($usage))return new WP_Error('ai_usage_evidence_unavailable','AI usage evidence is unavailable.');$actual=['month'=>[],'costs'=>[]];foreach($usage as $u)$actual['month'][(string)$u['stage']]=['count'=>(int)$u['quantity'],'cost'=>(float)$u['cost']];
  $sum=function(string $sql)use($wpdb):float|WP_Error{$wpdb->last_error='';$raw=$wpdb->get_var($sql);if(!empty($wpdb->last_error)||!is_numeric($raw))return new WP_Error('ai_usage_evidence_unavailable','AI usage evidence is unavailable.');return (float)$raw;};$dayCost=$sum($wpdb->prepare('SELECT COALESCE(SUM(actual_cost),0) FROM '.Tables::shop_ai_usage().' WHERE shop_key=%s AND occurred_at>=%s',$shop,$day));if($dayCost instanceof WP_Error)return $dayCost;$monthCost=$sum($wpdb->prepare('SELECT COALESCE(SUM(actual_cost),0) FROM '.Tables::shop_ai_usage().' WHERE shop_key=%s AND occurred_at>=%s',$shop,$month));if($monthCost instanceof WP_Error)return $monthCost;$runCost=0.0;if($runId!==''){$runCost=$sum($wpdb->prepare('SELECT COALESCE(SUM(actual_cost),0) FROM '.Tables::shop_ai_usage().' WHERE shop_key=%s AND run_id=%s',$shop,$runId));if($runCost instanceof WP_Error)return $runCost;}$actual['costs']['day']=$dayCost;$actual['costs']['month']=$monthCost;$actual['costs']['run']=$runCost;
  $projection=ShopAiPlan::evaluate($policy,$actual);$runBudget=(float)($projection['budgets']['run']??0);$explicit=$runContext!==null;$projection['run_context']=['run_id'=>$runId,'started_at'=>$runStart,'explicit'=>$explicit,'authoritative'=>$explicit];if($runBudget>0&&!$explicit){$projection['execution_allowed']=false;$projection['run_context']['reason']='EXPLICIT_RUN_CONTEXT_REQUIRED';}return $projection;
 }
}