<?php
declare(strict_types=1);
namespace DigiForge\Database;
use DigiForge\Core\Capabilities;
/** Versioned, additive schema migrations. dbDelta is used for WordPress-compatible table updates. */
final class Migrator {
    public function maybe_migrate(): void { if ((string) get_option('digiforge_db_version', '0') !== DIGIFORGE_DB_VERSION) { $this->migrate(); } }
    public function migrate(): void {
        global $wpdb; require_once ABSPATH . 'wp-admin/includes/upgrade.php'; $charset = $wpdb->get_charset_collate();
        $currentVersion = (int) get_option('digiforge_db_schema_version', 0);

        if ($currentVersion >= MigrationPlan::LATEST) {
            Capabilities::addDigital();
            Capabilities::addAi();
            delete_option('digiforge_last_migration_failure');
            update_option('digiforge_db_version', DIGIFORGE_DB_VERSION, false);
            return;
        }

        $existing_jobs_table = $wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s', $wpdb->esc_like(Tables::jobs())));
        if ($existing_jobs_table === Tables::jobs() && $currentVersion < 2) {
            $wpdb->query('UPDATE ' . Tables::jobs() . " SET idempotency_key = NULL WHERE idempotency_key = ''");
        }

        $baseSql = [
            'CREATE TABLE ' . Tables::settings() . " (setting_key varchar(191) NOT NULL, setting_value longtext NOT NULL, setting_type varchar(32) NOT NULL DEFAULT 'string', updated_at datetime NOT NULL, PRIMARY KEY  (setting_key), KEY updated_at (updated_at)) $charset;",
            'CREATE TABLE ' . Tables::audit_log() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, event_type varchar(100) NOT NULL, actor_id bigint(20) unsigned NOT NULL DEFAULT 0, object_type varchar(100) NOT NULL DEFAULT '', object_id varchar(191) NOT NULL DEFAULT '', context longtext NULL, created_at datetime NOT NULL, PRIMARY KEY  (id), KEY event_created (event_type,created_at), KEY object_lookup (object_type,object_id)) $charset;",
            'CREATE TABLE ' . Tables::jobs() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, job_type varchar(100) NOT NULL, state varchar(20) NOT NULL, payload longtext NULL, idempotency_key varchar(191) NULL DEFAULT NULL, scheduled_at datetime NULL, next_attempt_at datetime NULL, locked_by varchar(100) NULL, locked_at datetime NULL, lease_expires_at datetime NULL, completed_at datetime NULL, dead_lettered_at datetime NULL, attempts smallint unsigned NOT NULL DEFAULT 0, max_attempts smallint unsigned NOT NULL DEFAULT 3, last_error varchar(255) NOT NULL DEFAULT '', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), KEY state_schedule (state,scheduled_at), KEY retry_schedule (state,next_attempt_at), KEY lease_expiry (state,lease_expires_at), KEY type_state (job_type,state), UNIQUE KEY idempotency_key (idempotency_key)) $charset;",
            'CREATE TABLE ' . Tables::idempotency() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, operation_key varchar(191) NOT NULL, operation_type varchar(100) NOT NULL, status varchar(20) NOT NULL, response_hash char(64) NOT NULL DEFAULT '', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY operation_key (operation_key), KEY type_status (operation_type,status)) $charset;",
            'CREATE TABLE ' . Tables::health_events() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, component varchar(100) NOT NULL, status varchar(20) NOT NULL, error_code varchar(100) NOT NULL DEFAULT '', details longtext NULL, observed_at datetime NOT NULL, PRIMARY KEY  (id), KEY component_observed (component,observed_at), KEY status_observed (status,observed_at)) $charset;",
            'CREATE TABLE ' . Tables::opportunities() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, title varchar(191) NOT NULL, description longtext NULL, state varchar(20) NOT NULL DEFAULT 'NEW', idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY idempotency_key (idempotency_key), KEY state_updated (state,updated_at)) $charset;",
            'CREATE TABLE ' . Tables::product_families() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, opportunity_id bigint(20) unsigned NOT NULL, name varchar(191) NOT NULL, description longtext NULL, state varchar(20) NOT NULL DEFAULT 'DRAFT', idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY idempotency_key (idempotency_key), KEY opportunity_state (opportunity_id,state)) $charset;",
            'CREATE TABLE ' . Tables::products() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, product_family_id bigint(20) unsigned NOT NULL, name varchar(191) NOT NULL, description longtext NULL, state varchar(20) NOT NULL DEFAULT 'DRAFT', idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY idempotency_key (idempotency_key), KEY family_state (product_family_id,state)) $charset;",
            'CREATE TABLE ' . Tables::product_versions() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, product_id bigint(20) unsigned NOT NULL, version_label varchar(100) NOT NULL, notes longtext NULL, state varchar(20) NOT NULL DEFAULT 'DRAFT', idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY idempotency_key (idempotency_key), UNIQUE KEY product_version (product_id,version_label), KEY product_state (product_id,state)) $charset;",
            'CREATE TABLE ' . Tables::digital_products() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, product_id bigint(20) unsigned NOT NULL, product_version_id bigint(20) unsigned NOT NULL, name varchar(191) NOT NULL, category varchar(100) NOT NULL, state varchar(32) NOT NULL DEFAULT 'DRAFT', readiness longtext NULL, idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY product_version (product_version_id), UNIQUE KEY idempotency_key (idempotency_key), KEY product_category (product_id,category), KEY state_updated (state,updated_at)) $charset;",
            'CREATE TABLE ' . Tables::digital_files() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, digital_product_id bigint(20) unsigned NOT NULL, product_version_id bigint(20) unsigned NOT NULL, name varchar(191) NOT NULL, file_type varchar(32) NOT NULL, mime_type varchar(100) NOT NULL DEFAULT '', storage_reference varchar(255) NOT NULL DEFAULT '', checksum_sha256 char(64) NOT NULL DEFAULT '', status varchar(32) NOT NULL DEFAULT 'PENDING', idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY idempotency_key (idempotency_key), KEY product_version (digital_product_id,product_version_id), KEY status_updated (status,updated_at)) $charset;",
            'CREATE TABLE ' . Tables::digital_file_versions() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, digital_file_id bigint(20) unsigned NOT NULL, version_label varchar(100) NOT NULL, storage_reference varchar(255) NOT NULL DEFAULT '', checksum_sha256 char(64) NOT NULL DEFAULT '', byte_size bigint(20) unsigned NOT NULL DEFAULT 0, status varchar(32) NOT NULL DEFAULT 'PENDING', idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY file_version (digital_file_id,version_label), UNIQUE KEY idempotency_key (idempotency_key), KEY file_status (digital_file_id,status)) $charset;",
            'CREATE TABLE ' . Tables::digital_packages() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, digital_product_id bigint(20) unsigned NOT NULL, product_version_id bigint(20) unsigned NOT NULL, name varchar(191) NOT NULL, manifest longtext NULL, checksum_sha256 char(64) NOT NULL DEFAULT '', byte_size bigint(20) unsigned NOT NULL DEFAULT 0, generation_status varchar(32) NOT NULL DEFAULT 'PENDING', idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY idempotency_key (idempotency_key), KEY product_version (digital_product_id,product_version_id), KEY generation_updated (generation_status,updated_at)) $charset;",
            'CREATE TABLE ' . Tables::digital_previews() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, digital_product_id bigint(20) unsigned NOT NULL, digital_file_id bigint(20) unsigned NOT NULL, name varchar(191) NOT NULL, preview_reference varchar(255) NOT NULL DEFAULT '', status varchar(32) NOT NULL DEFAULT 'PENDING', idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY idempotency_key (idempotency_key), KEY product_file (digital_product_id,digital_file_id), KEY status_updated (status,updated_at)) $charset;",
            'CREATE TABLE ' . Tables::digital_templates() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, digital_product_id bigint(20) unsigned NOT NULL, digital_file_id bigint(20) unsigned NOT NULL, digital_preview_id bigint(20) unsigned NOT NULL, name varchar(191) NOT NULL, template_reference varchar(255) NOT NULL DEFAULT '', access_instructions longtext NULL, status varchar(32) NOT NULL DEFAULT 'DRAFT', idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY idempotency_key (idempotency_key), KEY product_file (digital_product_id,digital_file_id), KEY preview_status (digital_preview_id,status)) $charset;",
            'CREATE TABLE ' . Tables::digital_licenses() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, digital_product_id bigint(20) unsigned NOT NULL, name varchar(191) NOT NULL, license_type varchar(64) NOT NULL, terms longtext NULL, license_code_hash char(64) NOT NULL DEFAULT '', status varchar(32) NOT NULL DEFAULT 'ACTIVE', idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY idempotency_key (idempotency_key), KEY product_status (digital_product_id,status)) $charset;",
            'CREATE TABLE ' . Tables::digital_download_checks() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, digital_product_id bigint(20) unsigned NOT NULL, target_type varchar(32) NOT NULL, target_id bigint(20) unsigned NOT NULL, check_type varchar(64) NOT NULL, validation_result varchar(20) NOT NULL DEFAULT 'PENDING', failure_reason varchar(255) NOT NULL DEFAULT '', review_status varchar(20) NOT NULL DEFAULT 'UNREVIEWED', details longtext NULL, idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY idempotency_key (idempotency_key), KEY product_result (digital_product_id,validation_result), KEY target_check (target_type,target_id,check_type), KEY review_updated (review_status,updated_at)) $charset;",
        ];
        $integrationSql = [
            'CREATE TABLE ' . Tables::integrations() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, provider varchar(32) NOT NULL, environment varchar(20) NOT NULL DEFAULT 'sandbox', connection_key varchar(100) NOT NULL, display_name varchar(191) NOT NULL, status varchar(20) NOT NULL DEFAULT 'DISCONNECTED', enabled tinyint(1) NOT NULL DEFAULT 0, config longtext NOT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY provider_environment_connection (provider,environment,connection_key), KEY provider_environment_status (provider,environment,status), KEY enabled_updated (enabled,updated_at)) $charset;",
            'CREATE TABLE ' . Tables::integration_secrets() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, integration_id bigint(20) unsigned NOT NULL, secret_name varchar(100) NOT NULL, ciphertext longtext NOT NULL, fingerprint char(16) NOT NULL, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY integration_secret (integration_id,secret_name), KEY integration_updated (integration_id,updated_at)) $charset;",
        ];
        $researchSql = [
            'CREATE TABLE ' . Tables::research_sources() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, name varchar(191) NOT NULL, source_type varchar(64) NOT NULL, environment varchar(20) NOT NULL DEFAULT 'sandbox', enabled tinyint(1) NOT NULL DEFAULT 0, config longtext NULL, idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY idempotency_key (idempotency_key), KEY type_environment (source_type,environment), KEY enabled_updated (enabled,updated_at)) $charset;",
            'CREATE TABLE ' . Tables::research_observations() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, source_id bigint(20) unsigned NOT NULL, external_id varchar(191) NOT NULL DEFAULT '', title varchar(191) NOT NULL DEFAULT '', body longtext NULL, content_hash char(64) NOT NULL, observed_at datetime NOT NULL, provenance longtext NULL, idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY content_hash (content_hash), UNIQUE KEY idempotency_key (idempotency_key), KEY source_observed (source_id,observed_at)) $charset;",
            'CREATE TABLE ' . Tables::research_evidence() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, observation_id bigint(20) unsigned NOT NULL, evidence_type varchar(64) NOT NULL, value longtext NOT NULL, provenance longtext NULL, idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY idempotency_key (idempotency_key), KEY observation_type (observation_id,evidence_type)) $charset;",
            'CREATE TABLE ' . Tables::research_candidates() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, title varchar(191) NOT NULL, canonical_title varchar(255) NOT NULL, fingerprint char(64) NOT NULL, summary longtext NULL, score decimal(6,2) NOT NULL DEFAULT 0, score_version varchar(32) NOT NULL, score_inputs longtext NULL, review_status varchar(20) NOT NULL DEFAULT 'PENDING', opportunity_id bigint(20) unsigned NOT NULL DEFAULT 0, idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY fingerprint (fingerprint), UNIQUE KEY idempotency_key (idempotency_key), KEY review_score (review_status,score), KEY opportunity_id (opportunity_id)) $charset;",
            'CREATE TABLE ' . Tables::research_candidate_evidence() . " (candidate_id bigint(20) unsigned NOT NULL, evidence_id bigint(20) unsigned NOT NULL, created_at datetime NOT NULL, PRIMARY KEY  (candidate_id,evidence_id), KEY evidence_id (evidence_id)) $charset;",
            'CREATE TABLE ' . Tables::research_reviews() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, candidate_id bigint(20) unsigned NOT NULL, decision varchar(20) NOT NULL, notes longtext NULL, reviewed_by bigint(20) unsigned NOT NULL DEFAULT 0, reviewed_at datetime NOT NULL, PRIMARY KEY  (id), KEY candidate_reviewed (candidate_id,reviewed_at), KEY decision_reviewed (decision,reviewed_at)) $charset;",
        ];
        $aiSql = [
            'CREATE TABLE ' . Tables::ai_tasks() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, task_key varchar(100) NOT NULL, name varchar(191) NOT NULL, environment varchar(20) NOT NULL DEFAULT 'sandbox', required_capabilities longtext NULL, min_quality_tier smallint unsigned NOT NULL DEFAULT 0, max_latency_ms int unsigned NOT NULL DEFAULT 0, max_cost_per_1k decimal(12,6) NOT NULL DEFAULT 0, status varchar(20) NOT NULL DEFAULT 'ACTIVE', idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY task_environment (task_key,environment), UNIQUE KEY idempotency_key (idempotency_key), KEY status_updated (status,updated_at)) $charset;",
            'CREATE TABLE ' . Tables::ai_models() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, model_key varchar(100) NOT NULL, provider varchar(64) NOT NULL, environment varchar(20) NOT NULL DEFAULT 'sandbox', model_class varchar(64) NOT NULL, capabilities longtext NULL, quality_tier smallint unsigned NOT NULL DEFAULT 0, latency_ms int unsigned NOT NULL DEFAULT 0, cost_per_1k decimal(12,6) NOT NULL DEFAULT 0, fallback_order smallint unsigned NOT NULL DEFAULT 100, prohibited tinyint(1) NOT NULL DEFAULT 0, enabled tinyint(1) NOT NULL DEFAULT 0, idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY model_environment (model_key,provider,environment), UNIQUE KEY idempotency_key (idempotency_key), KEY route_order (environment,enabled,prohibited,fallback_order)) $charset;",
            'CREATE TABLE ' . Tables::ai_prompts() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, prompt_key varchar(100) NOT NULL, name varchar(191) NOT NULL, status varchar(20) NOT NULL DEFAULT 'ACTIVE', idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY prompt_key (prompt_key), UNIQUE KEY idempotency_key (idempotency_key), KEY status_updated (status,updated_at)) $charset;",
            'CREATE TABLE ' . Tables::ai_prompt_versions() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, prompt_id bigint(20) unsigned NOT NULL, version_label varchar(100) NOT NULL, system_text longtext NULL, instruction_text longtext NULL, template_text longtext NULL, input_schema_id varchar(100) NOT NULL DEFAULT '', input_schema_version varchar(64) NOT NULL DEFAULT '', output_schema_id varchar(100) NOT NULL DEFAULT '', output_schema_version varchar(64) NOT NULL DEFAULT '', input_schema longtext NULL, output_schema longtext NULL, status varchar(20) NOT NULL DEFAULT 'draft', checksum_sha256 char(64) NOT NULL, idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY prompt_version (prompt_id,version_label), UNIQUE KEY idempotency_key (idempotency_key), KEY checksum (checksum_sha256)) $charset;",
            'CREATE TABLE ' . Tables::ai_runs() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, task_id bigint(20) unsigned NOT NULL, model_id bigint(20) unsigned NOT NULL, prompt_version_id bigint(20) unsigned NOT NULL, environment varchar(20) NOT NULL, routing_decision longtext NOT NULL, input_schema_id varchar(100) NOT NULL DEFAULT '', input_schema_version varchar(64) NOT NULL DEFAULT '', output_schema_id varchar(100) NOT NULL DEFAULT '', output_schema_version varchar(64) NOT NULL DEFAULT '', input_payload longtext NULL, input_fingerprint char(64) NOT NULL, state varchar(32) NOT NULL DEFAULT 'DRAFT', provenance longtext NULL, idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY idempotency_key (idempotency_key), KEY state_updated (state,updated_at), KEY task_created (task_id,created_at), KEY prompt_model (prompt_version_id,model_id)) $charset;",
            'CREATE TABLE ' . Tables::ai_outputs() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, run_id bigint(20) unsigned NOT NULL, task_id bigint(20) unsigned NOT NULL, model_id bigint(20) unsigned NOT NULL, prompt_version_id bigint(20) unsigned NOT NULL, schema_id varchar(100) NOT NULL DEFAULT '', schema_version varchar(64) NOT NULL DEFAULT '', payload longtext NULL, source_input_fingerprint char(64) NOT NULL, review_state varchar(20) NOT NULL DEFAULT 'UNREVIEWED', idempotency_key varchar(191) NULL DEFAULT NULL, created_by bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY idempotency_key (idempotency_key), KEY run_created (run_id,created_at), KEY review_created (review_state,created_at)) $charset;",
            'CREATE TABLE ' . Tables::ai_usage() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, run_id bigint(20) unsigned NOT NULL, provider varchar(64) NOT NULL, model_key varchar(100) NOT NULL, environment varchar(20) NOT NULL, metering_unit varchar(32) NOT NULL, request_units bigint(20) unsigned NOT NULL DEFAULT 0, input_units bigint(20) unsigned NOT NULL DEFAULT 0, output_units bigint(20) unsigned NOT NULL DEFAULT 0, estimated_cost decimal(14,6) NOT NULL DEFAULT 0, currency char(3) NOT NULL DEFAULT 'USD', estimate_source varchar(100) NOT NULL DEFAULT 'manual', estimate_version varchar(64) NOT NULL DEFAULT 'v1', idempotency_key varchar(191) NULL DEFAULT NULL, created_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY idempotency_key (idempotency_key), KEY run_created (run_id,created_at), KEY provider_model (provider,model_key,environment)) $charset;",
            'CREATE TABLE ' . Tables::ai_reviews() . " (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, run_id bigint(20) unsigned NOT NULL, target_type varchar(20) NOT NULL, target_id bigint(20) unsigned NOT NULL, decision varchar(20) NOT NULL, notes longtext NULL, idempotency_key varchar(191) NULL DEFAULT NULL, reviewed_by bigint(20) unsigned NOT NULL DEFAULT 0, reviewed_at datetime NOT NULL, PRIMARY KEY  (id), UNIQUE KEY idempotency_key (idempotency_key), KEY run_reviewed (run_id,reviewed_at), KEY target_reviewed (target_type,target_id,reviewed_at)) $charset;",
        ];

        if ($currentVersion >= 7) {
            $sql = $aiSql;
        } elseif ($currentVersion === 6) {
            $sql = array_merge($researchSql, $aiSql);
        } elseif ($currentVersion === 5) {
            $sql = array_merge($integrationSql, $researchSql, $aiSql);
        } else {
            $sql = array_merge($baseSql, $integrationSql, $researchSql, $aiSql);
        }

        $schemaFailed = false;
        foreach ($sql as $statement) {
            $wpdb->last_error = '';
            dbDelta($statement);
            if ($wpdb->last_error !== '') { $schemaFailed = true; break; }
        }
        if ($schemaFailed) {
            update_option('digiforge_last_migration_failure',['error_code'=>'SCHEMA_UPDATE_FAILED','occurred_at'=>current_time('mysql',true)],false);
            return;
        }

        foreach (MigrationPlan::pending($currentVersion) as $version) { update_option('digiforge_db_schema_version', $version, false); }
        Capabilities::addDigital();
        Capabilities::addAi();
        delete_option('digiforge_last_migration_failure');
        update_option('digiforge_db_version', DIGIFORGE_DB_VERSION, false);
    }
}
