<?php
declare(strict_types=1);
use PHPUnit\Framework\TestCase;
final class EtsyWebhookIntakeContractTest extends TestCase {
 public function testVerifierIsSignatureFirstAndReplayBounded():void{$s=(string)file_get_contents(dirname(__DIR__,2).'/includes/Listings/EtsyWebhookVerifier.php');foreach(['hash_hmac','hash_equals','MAX_SKEW_SECONDS','whsec_','base64_decode','order.paid','order.canceled','order.shipped','order.delivered'] as $n)self::assertStringContainsString($n,$s);foreach(['wp_remote_','curl_exec(','CredentialVault'] as $n)self::assertStringNotContainsString($n,$s);}
 public function testPublicIngressIsSignatureFirstAndServerSecretOnly():void{$s=(string)file_get_contents(dirname(__DIR__,2).'/includes/REST/EtsyWebhookController.php');foreach(["'/etsy/webhook'","'permission_callback'=>'__return_true'","DIGIFORGE_ETSY_WEBHOOK_SECRET",'get_body()','EtsyWebhookIntake','external_execution_performed'] as $n)self::assertStringContainsString($n,$s);foreach(['get_param(\'secret\')','wp_remote_','CredentialVault::encrypt'] as $n)self::assertStringNotContainsString($n,$s);}
 public function testReadinessIsProtectedAndNeverExposesSecret():void{$c=(string)file_get_contents(dirname(__DIR__,2).'/includes/REST/EtsyWebhookController.php');self::assertStringContainsString('/etsy/webhook-readiness',$c);self::assertStringContainsString("current_user_can('manage_options')",$c);$r=(string)file_get_contents(dirname(__DIR__,2).'/includes/Listings/EtsyWebhookReadiness.php');foreach(['signing_secret_configured','secret_exposed',"['order.paid','order.canceled','order.shipped','order.delivered']"] as $n)self::assertStringContainsString($n,$r);self::assertStringNotContainsString("'secret'=>",$r);}
 public function testIntakeDeduplicatesBeforeAnyOrderMutation():void{$s=(string)file_get_contents(dirname(__DIR__,2).'/includes/Listings/EtsyWebhookIntake.php');self::assertStringContainsString('EtsyWebhookVerifier::verify',$s);self::assertStringContainsString('->claim(',$s);self::assertStringContainsString('EtsyOrderWebhookLifecycle',$s);}
 public function testDedupUsesAtomicInsertIgnore():void{$s=(string)file_get_contents(dirname(__DIR__,2).'/includes/Listings/EtsyWebhookDeduplicator.php');self::assertStringContainsString('INSERT IGNORE',$s);self::assertStringContainsString('if($inserted===false)',$s);self::assertStringContainsString('digiforge_idempotency',$s);self::assertStringContainsString('operation_key',$s);self::assertStringContainsString('operation_type',$s);self::assertStringContainsString('status',$s);self::assertStringContainsString('updated_at',$s);self::assertStringContainsString('FAILED',$s);self::assertStringContainsString('PROCESSED',$s);self::assertStringContainsString("'process_permitted'=>false",$s);self::assertStringContainsString('status',$s);}
}
