<?php
declare(strict_types=1);
use PHPUnit\Framework\TestCase;
final class EtsyMultipartImageBoundaryTest extends TestCase {
 public function testPlannerBoundsImageTypeSizeAndDoesNotPublish():void{$s=(string)file_get_contents(dirname(__DIR__,2).'/includes/Listings/EtsyMultipartImageRequest.php');foreach(['MAX_BYTES','image/jpeg','image/png','image/webp','sha256','publish_permitted','file_path'] as $n)self::assertStringContainsString($n,$s);foreach(['access_token','refresh_token','wp_remote_'] as $n)self::assertStringNotContainsString($n,$s);}
 public function testDigitalFileBindingIsSeparateFromImagePlanner():void{$s=(string)file_get_contents(dirname(__DIR__,2).'/includes/Listings/EtsyMultipartTransportBinder.php');foreach(['ETSY_MULTIPART_FILE_PREPARED','file_sha256','file_size'] as $n)self::assertStringContainsString($n,$s);$c=(string)file_get_contents(dirname(__DIR__,2).'/includes/Listings/EtsyControlledDraftExecutionCoordinator.php');self::assertStringContainsString('UPLOAD_FILE',$c);}
 public function testDigitalFilePlannerUsesCanonicalFilenameAndBinderMapsItToEtsyName():void{$p=(string)file_get_contents(dirname(__DIR__,2).'/includes/Listings/EtsyDraftListingOperations.php');self::assertStringContainsString("\$multipart['filename']??''",$p);self::assertStringNotContainsString("\$multipart['name']??''",$p);$b=(string)file_get_contents(dirname(__DIR__,2).'/includes/Listings/EtsyMultipartTransportBinder.php');self::assertStringContainsString("'name'=>(string)(\$multipart['filename']??'')",$b);$e=(string)file_get_contents(dirname(__DIR__,2).'/includes/Listings/EtsyControlledHttpExecutor.php');self::assertStringContainsString('name="name"',$e);}
 public function testDigitalFileClosureCapturesFilePlanAndEmitsNamePart():void{$s=(string)file_get_contents(dirname(__DIR__,2).'/includes/Listings/EtsyControlledHttpExecutor.php');self::assertStringContainsString('use ($sender,$method,$endpoint,$headers,$payload,$multipart,$multipartBytes,$operationId,$filePlan)',$s);self::assertStringContainsString('if($filePlan)',$s);self::assertStringContainsString('name="name"',$s);}
 public function testExecutorHasDedicatedMultipartBoundary():void{$s=(string)file_get_contents(dirname(__DIR__,2).'/includes/Listings/EtsyControlledHttpExecutor.php');foreach(['multipart/form-data','Content-Disposition','Content-Type','file_get_contents($asset)','multipart','$multipartBytes,$operationId','rank','ETSY_MULTIPART_IMAGE_PREPARED','hash_equals'] as $n)self::assertStringContainsString($n,$s);}
 public function testExactValidatedBytesAreBoundBeforeCredentialConsumption():void{$s=(string)file_get_contents(dirname(__DIR__,2).'/includes/Listings/EtsyControlledHttpExecutor.php');$read=strpos($s,'$multipartBytes=file_get_contents($asset)');$consume=strpos($s,'$credential->consume');self::assertNotFalse($read);self::assertNotFalse($consume);self::assertLessThan($consume,$read);self::assertStringContainsString("hash('sha256',\$multipartBytes)",$s);self::assertStringContainsString('strlen($multipartBytes)!==$expectedSize',$s);self::assertSame(1,substr_count($s,'file_get_contents($asset)'));}
 public function testMultipartBytesAreValidatedBeforeCredentialRetrieval():void{$s=(string)file_get_contents(dirname(__DIR__,2).'/includes/Listings/EtsyControlledHttpExecutor.php');$read=strpos($s,'$multipartBytes=file_get_contents($asset)');$interlock=strpos($s,'EtsyLiveTransportInterlock::authorize($prepared)');$retrieve=strpos($s,'EtsyScopedCredentialRetriever())->retrieve');self::assertNotFalse($read);self::assertNotFalse($interlock);self::assertNotFalse($retrieve);self::assertLessThan($interlock,$read);self::assertLessThan($retrieve,$read);self::assertLessThan($retrieve,$interlock);}
 public function testMultipartDoesNotBecomeJsonBody():void{$s=(string)file_get_contents(dirname(__DIR__,2).'/includes/Listings/EtsyControlledHttpExecutor.php');self::assertStringContainsString('if ($multipart!==null)',$s);self::assertStringContainsString('multipart_integrity',$s);self::assertStringContainsString('multipart_asset',$s);self::assertStringContainsString('} elseif ($payload!==[]',$s);}
}
