<?php

declare(strict_types=1);

use PHPUnit\Framework\TestCase;

final class PrintifyCatalogSyncServiceStructureTest extends TestCase
{
    private function source(): string{$source=file_get_contents(dirname(__DIR__,2).'/includes/POD/PrintifyCatalogSyncService.php');self::assertIsString($source);return $source;}
    public function testCatalogNetworkReadsRequireScopedPrintifyAuthorization(): void{$source=$this->source();self::assertSame(2,substr_count($source,"Settings::is_enabled('printify')"));self::assertStringContainsString('digiforge_printify_locked',$source);self::assertStringContainsString('Scoped Printify authorization is required before catalog network access.',$source);}
    public function testSyncIsCredentialVaultedAndFailClosed(): void{$source=$this->source();self::assertStringContainsString("['provider']??'')!=='printify'",$source);self::assertStringContainsString("['status']??'')!=='CONFIGURED'",$source);self::assertStringContainsString("empty(\$integration['enabled'])",$source);self::assertStringContainsString('CredentialVault::decrypt',$source);self::assertStringContainsString('personal_access_token',$source);self::assertStringContainsString('access_token',$source);self::assertStringContainsString('PrintifyCatalogClient',$source);}
    public function testSyncUsesTokenPerReadAndPersistsNormalizedVariants(): void{$source=$this->source();self::assertStringContainsString('blueprint($token,$blueprintId)',$source);self::assertStringContainsString('providers($token,$blueprintId)',$source);self::assertStringContainsString('variants($token,$blueprintId,$providerId)',$source);self::assertStringContainsString('new PrintifyCatalogPersistence()',$source);self::assertStringContainsString('persistVariant($raw)',$source);self::assertStringContainsString('unset($token)',$source);}
    public function testSupplierEvidenceIsNormalizedBeforePersistence(): void{$source=$this->source();self::assertStringContainsString('moneyEvidence',$source);self::assertStringContainsString('round($value/100,4)',$source);self::assertStringContainsString('digiforge_printify_cost',$source);self::assertStringContainsString('availabilityEvidence',$source);self::assertStringContainsString("?'AVAILABLE':",$source);self::assertStringContainsString("?'UNAVAILABLE':'UNKNOWN'",$source);self::assertStringContainsString("\$observed=gmdate('c')",$source);}
    public function testShippingEvidenceIsFetchedAndPersistedReadOnly(): void{$source=$this->source();self::assertStringContainsString('shipping($token,$blueprintId,$providerId)',$source);self::assertStringContainsString('shippingEvidence($shipping)',$source);self::assertStringContainsString('if(is_wp_error($shipping))return $shipping',$source);self::assertStringContainsString("'shipping_profile'=>\$shippingProfile",$source);self::assertStringContainsString('ksort($out,SORT_STRING)',$source);}
    public function testSyncRemainsProviderReadOnly(): void{$source=$this->source();self::assertStringNotContainsString('createOrder',$source);self::assertStringNotContainsString('publishProduct',$source);self::assertStringNotContainsString('wp_remote_post',$source);self::assertStringNotContainsString('wp_remote_put',$source);self::assertStringNotContainsString('wp_remote_delete',$source);}
}
