<?php

declare(strict_types=1);

namespace DigiForge\POD;

use DigiForge\Database\Tables;
use WP_Error;

final class BusinessScopeRepository
{
    public function replay(array $input,?string $idempotencyKey): array|WP_Error|null
    {
        global $wpdb;$key=$idempotencyKey===null?null:sanitize_text_field($idempotencyKey);if($key===null||$key==='')return null;
        $wpdb->flush();$queryResult=$wpdb->query($wpdb->prepare('SELECT * FROM '.Tables::pod_business_mappings().' WHERE idempotency_key=%s LIMIT 1',$key));if($queryResult===false||!empty($wpdb->last_error))return new WP_Error('digiforge_idempotency_evidence_unavailable','Idempotency evidence could not be read.',['status'=>503,'retry_permitted'=>false,'external_execution_authorized'=>false]);$existing=isset($wpdb->last_result[0])?(array)$wpdb->last_result[0]:null;if(!empty($wpdb->last_error))return new WP_Error('digiforge_idempotency_evidence_unavailable','Idempotency evidence could not be read.',['status'=>503,'retry_permitted'=>false,'external_execution_authorized'=>false]);if(!is_array($existing))return null;
        $fingerprint=$this->requestFingerprint($input);if(is_wp_error($fingerprint))return $fingerprint;
        return hash_equals((string)($existing['request_fingerprint']??''),$fingerprint)?$existing:new WP_Error('digiforge_idempotency_conflict','Idempotency key is already bound to a different business scope or mapping.',['status'=>409]);
    }

    /** Fail closed when the mapping no longer has a currently ACTIVE, relationally valid owner. */
    public function assertActiveOwnershipForMapping(int $mappingId): array|WP_Error
    {
        global $wpdb;if($mappingId<1)return new WP_Error('digiforge_scope_validation','Valid provider mapping is required.',['status'=>400]);
        $sql='SELECT m.*,b.business_key,s.store_key,p.program_key FROM '.Tables::pod_business_mappings().' m INNER JOIN '.Tables::businesses().' b ON b.id=m.business_id INNER JOIN '.Tables::stores().' s ON s.id=m.store_id AND s.business_id=b.id INNER JOIN '.Tables::product_programs().' p ON p.id=m.product_program_id AND p.business_id=b.id AND p.store_id=s.id WHERE m.provider_mapping_id=%d AND m.state=%s AND m.approved_by>0 AND m.approved_at IS NOT NULL AND b.status=%s AND s.status=%s AND p.status=%s LIMIT 1';
        $wpdb->flush();$queryResult=$wpdb->query($wpdb->prepare($sql,$mappingId,'APPROVED','ACTIVE','ACTIVE','ACTIVE'));
        if($queryResult===false||!empty($wpdb->last_error))return new WP_Error('digiforge_scope_evidence_unavailable','Active POD ownership evidence could not be read.',['status'=>500]);
        $row=isset($wpdb->last_result[0])?(array)$wpdb->last_result[0]:null;
        if(!empty($wpdb->last_error))return new WP_Error('digiforge_scope_evidence_unavailable','Active POD ownership evidence could not be read.',['status'=>500]);
        if(!is_array($row))return new WP_Error('digiforge_scope_inactive','Provider mapping has no approved active business/store/product-program ownership.',['status'=>409]);
        if(sanitize_key((string)$row['business_key'])===BusinessScope::DIGICRAFTIFY_GOODS&&strtoupper((string)$row['program_key'])!==BusinessScope::PERSONALIZED_POD)return new WP_Error('digiforge_scope_validation','DigiCraftifyGoods is restricted to PERSONALIZED_POD',['status'=>409]);
        return $row;
    }

    public function approveMapping(int $id): array|WP_Error
    {
        global $wpdb;$reviewer=get_current_user_id();if($reviewer<1)return new WP_Error('digiforge_scope_reviewer_required','Authenticated human reviewer required.',['status'=>403]);
        $now=current_time('mysql',true);$wpdb->last_error='';$ok=$wpdb->update(Tables::pod_business_mappings(),['state'=>'APPROVED','approved_by'=>$reviewer,'approved_at'=>$now,'updated_at'=>$now],['id'=>$id,'state'=>'DRAFT']);
        if($ok!==1){if(!empty($wpdb->last_error))return new WP_Error('digiforge_scope_approval_persistence_failed','Ownership approval could not be persisted.',['status'=>503,'retry_permitted'=>false,'external_execution_authorized'=>false]);return new WP_Error('digiforge_scope_transition','Ownership must exist in DRAFT state and approval cannot be overwritten.',['status'=>409]);}
        $wpdb->flush();$queryResult=$wpdb->query($wpdb->prepare('SELECT * FROM '.Tables::pod_business_mappings().' WHERE id=%d',$id));$approved=isset($wpdb->last_result[0])?(array)$wpdb->last_result[0]:null;if($queryResult===false||!is_array($approved)||!empty($wpdb->last_error))return new WP_Error('digiforge_scope_confirmation_unavailable','Ownership approval completed but confirmation evidence is unavailable; do not retry automatically.',['status'=>503,'retry_permitted'=>false,'external_execution_authorized'=>false]);return $approved;
    }

    public function createMapping(array $input,?string $idempotencyKey=null,bool $manageTransaction=true): array|WP_Error
    {
        global $wpdb;$replay=$this->replay($input,$idempotencyKey);if($replay!==null)return $replay;
        $productVersionId=absint($input['product_version_id']??0);$providerMappingId=absint($input['provider_mapping_id']??0);if($productVersionId<1||$providerMappingId<1)return new WP_Error('digiforge_scope_validation','product_version_id and provider_mapping_id are required.',['status'=>400]);
        $key=$idempotencyKey===null?null:sanitize_text_field($idempotencyKey);if($key==='')$key=null;$fingerprint=$this->requestFingerprint($input);if(is_wp_error($fingerprint))return $fingerprint;
        if($manageTransaction){$wpdb->last_error='';$started=$wpdb->query('START TRANSACTION');if($started===false||!empty($wpdb->last_error))return new WP_Error('digiforge_scope_transaction_unavailable','POD ownership transaction could not be started.',['status'=>500]);}
        try{
            try{$scope=BusinessScope::resolveConfigured($input);}catch(\InvalidArgumentException $e){if($manageTransaction)$this->rollbackPreservingPrimaryFailure();return new WP_Error('digiforge_scope_validation',$e->getMessage(),['status'=>409]);}catch(\RuntimeException $e){if($manageTransaction)$this->rollbackPreservingPrimaryFailure();return new WP_Error('digiforge_scope_evidence_unavailable','Configured POD scope registry evidence could not be read.',['status'=>503,'retry_permitted'=>false,'external_execution_authorized'=>false]);}
            $businessRef=sanitize_key((string)$input['business_id']);$storeRef=sanitize_key((string)$input['store_id']);
            $wpdb->flush();$queryResult=$wpdb->query($wpdb->prepare('SELECT id,business_key FROM '.Tables::businesses().' WHERE id=%d AND status=%s FOR UPDATE',$scope['business_id'],'ACTIVE'));$business=isset($wpdb->last_result[0])?(array)$wpdb->last_result[0]:null;if($queryResult===false||!empty($wpdb->last_error)){if($manageTransaction)$this->rollbackPreservingPrimaryFailure();return new WP_Error('digiforge_scope_evidence_unavailable','Business scope evidence could not be read.',['status'=>500]);}$wpdb->flush();$queryResult=$wpdb->query($wpdb->prepare('SELECT id,store_key FROM '.Tables::stores().' WHERE id=%d AND business_id=%d AND status=%s FOR UPDATE',$scope['store_id'],$scope['business_id'],'ACTIVE'));$store=isset($wpdb->last_result[0])?(array)$wpdb->last_result[0]:null;if($queryResult===false||!empty($wpdb->last_error)){if($manageTransaction)$this->rollbackPreservingPrimaryFailure();return new WP_Error('digiforge_scope_evidence_unavailable','Store scope evidence could not be read.',['status'=>500]);}$wpdb->flush();$queryResult=$wpdb->query($wpdb->prepare('SELECT id,program_key FROM '.Tables::product_programs().' WHERE id=%d AND business_id=%d AND store_id=%d AND status=%s FOR UPDATE',$scope['product_program_id'],$scope['business_id'],$scope['store_id'],'ACTIVE'));$program=isset($wpdb->last_result[0])?(array)$wpdb->last_result[0]:null;if($queryResult===false||!empty($wpdb->last_error)){if($manageTransaction)$this->rollbackPreservingPrimaryFailure();return new WP_Error('digiforge_scope_evidence_unavailable','Product-program scope evidence could not be read.',['status'=>500]);}
            $businessMatches=is_array($business)&&($businessRef===(string)$business['id']||$businessRef===sanitize_key((string)$business['business_key']));$storeMatches=is_array($store)&&($storeRef===(string)$store['id']||$storeRef===sanitize_key((string)$store['store_key']));if(!$businessMatches||!$storeMatches||!is_array($program)||strtoupper((string)$program['program_key'])!==$scope['product_program']){if($manageTransaction)$this->rollbackPreservingPrimaryFailure();return new WP_Error('digiforge_scope_changed','Business/store/product-program keys changed during ownership resolution.',['status'=>409]);}
            if(sanitize_key((string)$business['business_key'])===BusinessScope::DIGICRAFTIFY_GOODS&&$scope['product_program']!==BusinessScope::PERSONALIZED_POD){if($manageTransaction)$this->rollbackPreservingPrimaryFailure();return new WP_Error('digiforge_scope_validation','DigiCraftifyGoods is restricted to PERSONALIZED_POD',['status'=>409]);}
            $wpdb->flush();$queryResult=$wpdb->query($wpdb->prepare('SELECT product_version_id FROM '.Tables::pod_mappings().' WHERE id=%d FOR UPDATE',$providerMappingId));$provider=isset($wpdb->last_result[0])?(array)$wpdb->last_result[0]:null;if($queryResult===false||!empty($wpdb->last_error)){if($manageTransaction)$this->rollbackPreservingPrimaryFailure();return new WP_Error('digiforge_scope_evidence_unavailable','Provider mapping evidence could not be read.',['status'=>500]);}if(!is_array($provider)||(int)$provider['product_version_id']!==$productVersionId){if($manageTransaction)$this->rollbackPreservingPrimaryFailure();return new WP_Error('digiforge_scope_relationship','Provider mapping must exist and match the product version.',['status'=>409]);}
            $wpdb->flush();$queryResult=$wpdb->query($wpdb->prepare('SELECT * FROM '.Tables::pod_business_mappings().' WHERE product_version_id=%d AND provider_mapping_id=%d LIMIT 1 FOR UPDATE',$productVersionId,$providerMappingId));$owner=isset($wpdb->last_result[0])?(array)$wpdb->last_result[0]:null;if($queryResult===false||!empty($wpdb->last_error)){if($manageTransaction)$this->rollbackPreservingPrimaryFailure();return new WP_Error('digiforge_scope_evidence_unavailable','POD ownership evidence could not be read.',['status'=>500]);}if(is_array($owner)){if($key!==null&&hash_equals((string)($owner['idempotency_key']??''),$key)&&hash_equals((string)($owner['request_fingerprint']??''),$fingerprint)){if($manageTransaction){$wpdb->last_error='';$committed=$wpdb->query('COMMIT');if($committed===false||!empty($wpdb->last_error))return new WP_Error('digiforge_scope_replay_commit_unknown','POD ownership replay commit outcome is unknown; do not retry automatically.',['status'=>503,'retry_permitted'=>false,'external_execution_authorized'=>false]);}return $owner;}if($manageTransaction)$this->rollbackPreservingPrimaryFailure();return new WP_Error('digiforge_scope_ownership_conflict','Product/provider mapping already has business ownership.',['status'=>409]);}
            $now=current_time('mysql',true);$inserted=$wpdb->insert(Tables::pod_business_mappings(),['business_id'=>$scope['business_id'],'store_id'=>$scope['store_id'],'product_program_id'=>$scope['product_program_id'],'product_version_id'=>$productVersionId,'provider_mapping_id'=>$providerMappingId,'state'=>'DRAFT','request_fingerprint'=>$fingerprint,'idempotency_key'=>$key,'created_by'=>get_current_user_id(),'created_at'=>$now,'updated_at'=>$now]);if($inserted!==1){if($manageTransaction)$this->rollbackPreservingPrimaryFailure();$wpdb->flush();$queryResult=$wpdb->query($wpdb->prepare('SELECT * FROM '.Tables::pod_business_mappings().' WHERE product_version_id=%d AND provider_mapping_id=%d LIMIT 1',$productVersionId,$providerMappingId));$winner=isset($wpdb->last_result[0])?(array)$wpdb->last_result[0]:null;if($queryResult===false||!empty($wpdb->last_error))return new WP_Error('digiforge_scope_race_evidence_unavailable','Concurrent ownership evidence could not be read; do not retry automatically.',['status'=>503,'retry_permitted'=>false,'external_execution_authorized'=>false]);if(is_array($winner)&&$key!==null&&hash_equals((string)($winner['idempotency_key']??''),$key)&&hash_equals((string)($winner['request_fingerprint']??''),$fingerprint))return $winner;if(is_array($winner))return new WP_Error('digiforge_scope_ownership_conflict','Product/provider mapping was concurrently assigned business ownership.',['status'=>409,'retry_permitted'=>false,'external_execution_authorized'=>false]);return new WP_Error('digiforge_scope_create_failed','Unable to create scoped POD mapping.',['status'=>500,'retry_permitted'=>false,'external_execution_authorized'=>false]);}
            $wpdb->flush();$queryResult=$wpdb->query($wpdb->prepare('SELECT * FROM '.Tables::pod_business_mappings().' WHERE id=%d',(int)$wpdb->insert_id));$created=isset($wpdb->last_result[0])?(array)$wpdb->last_result[0]:null;if($queryResult===false||!is_array($created)||!empty($wpdb->last_error)){if($manageTransaction)$this->rollbackPreservingPrimaryFailure();return new WP_Error('digiforge_scope_confirmation_unavailable','POD ownership was written but confirmation evidence is unavailable; do not retry automatically.',['status'=>503,'retry_permitted'=>false,'external_execution_authorized'=>false]);}if($manageTransaction){$wpdb->last_error='';$committed=$wpdb->query('COMMIT');if($committed===false||!empty($wpdb->last_error))return new WP_Error('digiforge_scope_commit_unknown','POD ownership commit outcome is unknown; do not retry automatically.',['status'=>503,'retry_permitted'=>false,'external_execution_authorized'=>false]);}return $created;
        }catch(\Throwable){if($manageTransaction)$this->rollbackPreservingPrimaryFailure();return new WP_Error('digiforge_scope_create_failed','Unable to create scoped POD mapping.',['status'=>500]);}
    }

    private function rollbackPreservingPrimaryFailure(): void
    {
        global $wpdb;$wpdb->last_error='';$rolledBack=$wpdb->query('ROLLBACK');if($rolledBack===false||!empty($wpdb->last_error)){error_log('[DigiForge] pod_scope_rollback_failed primary_error_preserved=true operator_attention_required=true');}
    }

    private function requestFingerprint(array $input): string|WP_Error
    {
        $productVersionId=absint($input['product_version_id']??0);$providerMappingId=absint($input['provider_mapping_id']??0);$business=sanitize_key((string)($input['business_id']??''));$store=sanitize_key((string)($input['store_id']??''));$program=strtoupper(trim((string)($input['product_program']??'')));
        if($productVersionId<1||$providerMappingId<1||$business===''||$store===''||$program==='')return new WP_Error('digiforge_scope_validation','Complete business/store/program and mapping identity is required.',['status'=>400]);
        $payload=wp_json_encode(['business_ref'=>$business,'store_ref'=>$store,'product_program'=>$program,'product_version_id'=>$productVersionId,'provider_mapping_id'=>$providerMappingId]);if(!is_string($payload))return new WP_Error('digiforge_scope_validation','Unable to fingerprint scope request.',['status'=>400]);return hash('sha256',$payload);
    }
}
