<?php
declare(strict_types=1);
namespace DigiForge\POD;
use DigiForge\Database\Tables;

/** Read-only drill-down for production provenance anomalies. Never authorizes execution or retry. */
final class ProductionProvenanceIntegrityReadModel{
 public function recent(int $limit=50):array{
  $limit=max(1,min(200,$limit));global $wpdb;$items=[];
  $queryStates=[];$wpdb->last_error='';$bindings=$wpdb->get_results($wpdb->prepare("SELECT b.authorization_hash,b.package_id,b.package_hash,p.package_hash AS actual_package_hash FROM ".Tables::pod_authorization_bindings()." b LEFT JOIN ".Tables::pod_authorization_packages()." p ON p.id=b.package_id WHERE p.id IS NULL OR p.package_hash<>b.package_hash ORDER BY b.id DESC LIMIT %d",$limit),ARRAY_A);$queryStates['bindings']=is_array($bindings)&&empty($wpdb->last_error)?'AVAILABLE':'UNAVAILABLE';
  foreach((array)$bindings as $row)$items[]=['type'=>'BINDING_PACKAGE_MISMATCH']+$row;
  if(count($items)<$limit){$remaining=$limit-count($items);$wpdb->last_error='';$closures=$wpdb->get_results($wpdb->prepare("SELECT c.authorization_hash,c.package_id,c.package_hash,p.package_hash AS actual_package_hash FROM ".Tables::pod_lifecycle_closures()." c LEFT JOIN ".Tables::pod_authorization_packages()." p ON p.id=c.package_id WHERE p.id IS NULL OR p.package_hash<>c.package_hash ORDER BY c.id DESC LIMIT %d",$remaining),ARRAY_A);$queryStates['closures']=is_array($closures)&&empty($wpdb->last_error)?'AVAILABLE':'UNAVAILABLE';foreach((array)$closures as $row)$items[]=['type'=>'CLOSURE_PACKAGE_MISMATCH']+$row;}
  if(count($items)<$limit){$remaining=$limit-count($items);$wpdb->last_error='';$disagreements=$wpdb->get_results($wpdb->prepare("SELECT b.authorization_hash,b.package_id,b.package_hash,c.package_id AS closure_package_id,c.package_hash AS actual_package_hash FROM ".Tables::pod_authorization_bindings()." b INNER JOIN ".Tables::pod_lifecycle_closures()." c ON c.authorization_hash=b.authorization_hash WHERE b.package_id<>c.package_id OR b.package_hash<>c.package_hash ORDER BY b.id DESC LIMIT %d",$remaining),ARRAY_A);$queryStates['disagreements']=is_array($disagreements)&&empty($wpdb->last_error)?'AVAILABLE':'UNAVAILABLE';foreach((array)$disagreements as $row)$items[]=['type'=>'BINDING_CLOSURE_MISMATCH']+$row;}
  if(count($items)<$limit){$remaining=$limit-count($items);$wpdb->last_error='';$legacy=$wpdb->get_results($wpdb->prepare("SELECT n.authorization_hash,0 AS package_id,'' AS package_hash,NULL AS actual_package_hash FROM ".Tables::pod_execution_nonces()." n LEFT JOIN ".Tables::pod_authorization_bindings()." b ON b.authorization_hash=n.authorization_hash LEFT JOIN ".Tables::pod_lifecycle_closures()." c ON c.authorization_hash=n.authorization_hash WHERE b.id IS NULL AND c.id IS NULL ORDER BY n.id DESC LIMIT %d",$remaining),ARRAY_A);$queryStates['legacy']=is_array($legacy)&&empty($wpdb->last_error)?'AVAILABLE':'UNAVAILABLE';foreach((array)$legacy as $row)$items[]=['type'=>'LEGACY_UNBOUND']+$row;}
  foreach($items as &$item){$auth=(string)$item['authorization_hash'];$item['historical_evidence']=false;$item['retry_permitted']=false;$item['external_execution_authorized']=false;
   $wpdb->last_error='';$item['outcome']=$wpdb->get_row($wpdb->prepare('SELECT outcome_type,outcome_hash,created_at FROM '.Tables::pod_execution_outcomes().' WHERE authorization_hash=%s LIMIT 1',$auth),ARRAY_A);$outcomeAvailable=empty($wpdb->last_error);if(!$outcomeAvailable)$queryStates['outcome_correlation']='UNAVAILABLE';elseif(!isset($queryStates['outcome_correlation']))$queryStates['outcome_correlation']='AVAILABLE';
   $wpdb->last_error='';$item['closure']=$wpdb->get_row($wpdb->prepare('SELECT outcome_state,closure_hash,external_execution_state,created_at FROM '.Tables::pod_lifecycle_closures().' WHERE authorization_hash=%s LIMIT 1',$auth),ARRAY_A);$closureAvailable=empty($wpdb->last_error);if(!$closureAvailable)$queryStates['closure_correlation']='UNAVAILABLE';elseif(!isset($queryStates['closure_correlation']))$queryStates['closure_correlation']='AVAILABLE';
   if(!$outcomeAvailable||!$closureAvailable){$item['correlation_hash']=null;$item['acknowledgement']=null;$item['operator_state']='EVIDENCE_UNAVAILABLE';$item['evidence_state']='UNAVAILABLE';continue;}
   $item['correlation_hash']=hash('sha256',implode('|',[$item['type'],$auth,(string)$item['package_id'],(string)$item['package_hash'],(string)($item['actual_package_hash']??''),(string)($item['outcome']['outcome_hash']??''),(string)($item['closure']['closure_hash']??'')]));
   $wpdb->last_error='';$ack=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Tables::pod_provenance_integrity_acknowledgements().' WHERE correlation_hash=%s LIMIT 1',$item['correlation_hash']),ARRAY_A);$ackAvailable=empty($wpdb->last_error);if(!$ackAvailable)$queryStates['acknowledgement']='UNAVAILABLE';elseif(!isset($queryStates['acknowledgement']))$queryStates['acknowledgement']='AVAILABLE';$item['acknowledgement']=$ackAvailable?$ack:null;$item['operator_state']=!$ackAvailable?'EVIDENCE_UNAVAILABLE':(is_array($ack)?'ACKNOWLEDGED':'OPEN');$item['evidence_state']=$ackAvailable?'AVAILABLE':'UNAVAILABLE';if($ackAvailable)ProductionProvenanceIntegrityEvidenceRepository::observe($item);
  }unset($item);
  $live=[];foreach($items as $item){$hash=(string)($item['correlation_hash']??'');if($hash!=='')$live[$hash]=true;}if(count($items)<$limit){foreach(ProductionProvenanceIntegrityEvidenceRepository::recent($limit-count($items)) as $historical){if(($historical['query_state']??'')==='UNAVAILABLE'){$queryStates['historical_evidence']='UNAVAILABLE';break;}$queryStates['historical_evidence']=$queryStates['historical_evidence']??'AVAILABLE';$hash=(string)($historical['correlation_hash']??'');if(isset($live[$hash]))continue;$wpdb->last_error='';$ack=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Tables::pod_provenance_integrity_acknowledgements().' WHERE correlation_hash=%s LIMIT 1',$hash),ARRAY_A);if(!empty($wpdb->last_error)){$queryStates['historical_acknowledgement']='UNAVAILABLE';$historical['acknowledgement']=null;$historical['operator_state']='EVIDENCE_UNAVAILABLE';$historical['evidence_state']='UNAVAILABLE';}else{$queryStates['historical_acknowledgement']=$queryStates['historical_acknowledgement']??'AVAILABLE';$historical['acknowledgement']=$ack;$historical['operator_state']=is_array($ack)?'ACKNOWLEDGED':'HISTORICAL';$historical['evidence_state']='AVAILABLE';}$historical['retry_permitted']=false;$historical['external_execution_authorized']=false;$items[]=$historical;if(count($items)>=$limit)break;}}
  $open=0;$acknowledged=0;$historical=0;$current=0;foreach($items as $item){if(!empty($item['historical_evidence']))$historical++;else $current++;if(($item['operator_state']??'OPEN')==='ACKNOWLEDGED')$acknowledged++;elseif(($item['operator_state']??'OPEN')==='OPEN')$open++;}$unavailable=array_keys(array_filter($queryStates,static fn(string $state):bool=>$state==='UNAVAILABLE'));return ['items'=>$items,'count'=>count($items),'current_count'=>$current,'historical_count'=>$historical,'open_count'=>$open,'acknowledged_count'=>$acknowledged,'count_scope'=>'BOUNDED_EVIDENCE_WINDOW','window_limit'=>$limit,'exhaustive'=>false,'query_state'=>$unavailable===[]?'AVAILABLE':'PARTIAL_UNAVAILABLE','query_states'=>$queryStates,'unavailable_sources'=>$unavailable,'read_only'=>true,'retry_permitted'=>false,'external_execution_authorized'=>false];
 }
}
