<?php
declare(strict_types=1);
namespace DigiForge\POD;
use DigiForge\Database\Tables;
use DigiForge\Orders\Repository as OrderRepository;
use WP_Error;

/** Immutable review package. It never grants or performs external provider execution. */
final class ProductionAuthorizationRepository
{
 public function create(int $orderId,int $renderEvidenceId):array|WP_Error{
  global $wpdb;$readiness=(new OrderRepository())->readiness($orderId);if(is_wp_error($readiness))return $readiness;if(empty($readiness['ready']))return new WP_Error('authorization_not_ready','Current order readiness is required.',['status'=>409]);
  $wpdb->last_error='';$wpdb->flush();$queryResult=$wpdb->query($wpdb->prepare('SELECT * FROM '.Tables::pod_render_evidence().' WHERE id=%d AND order_id=%d AND review_status=%s AND reviewed_by>0 AND reviewed_at IS NOT NULL AND external_execution_performed=0',$renderEvidenceId,$orderId,'APPROVED'));if($queryResult===false||!empty($wpdb->last_error))return new WP_Error('authorization_evidence_unavailable','Production authorization query failed closed.',['status'=>503,'retry_permitted'=>false,'external_execution_authorized'=>false]);$render=(isset($wpdb->last_result[0]) ? (array) $wpdb->last_result[0] : null);if(!empty($wpdb->last_error))return new WP_Error('authorization_evidence_unavailable','Production authorization evidence is unavailable; package creation is blocked.',['status'=>503,'external_execution_authorized'=>false]);if(!is_array($render))return new WP_Error('authorization_render_required','Approved human-reviewed render evidence is required.',['status'=>409]);
  $certified=(new RenderArtifactVerifier())->assertCertified($render);if($certified instanceof WP_Error)return $certified;
  $scope=(new BusinessScopeRepository())->assertActiveOwnershipForMapping((int)$render['provider_mapping_id']);if(is_wp_error($scope))return $scope;
  $readinessHash=hash('sha256',wp_json_encode($readiness));$canonical=wp_json_encode(['order_id'=>$orderId,'render_evidence_id'=>$renderEvidenceId,'render_evidence_hash'=>(string)$render['evidence_hash'],'provider_mapping_id'=>(int)$render['provider_mapping_id'],'ownership_mapping_id'=>(int)$scope['id'],'readiness_hash'=>$readinessHash]);$packageHash=hash('sha256',(string)$canonical);
  $wpdb->last_error='';$wpdb->flush();$queryResult=$wpdb->query($wpdb->prepare('SELECT * FROM '.Tables::pod_authorization_packages().' WHERE package_hash=%s',$packageHash));if($queryResult===false||!empty($wpdb->last_error))return new WP_Error('authorization_evidence_unavailable','Production authorization query failed closed.',['status'=>503,'retry_permitted'=>false,'external_execution_authorized'=>false]);$old=(isset($wpdb->last_result[0]) ? (array) $wpdb->last_result[0] : null);if(!empty($wpdb->last_error))return new WP_Error('authorization_evidence_unavailable','Production authorization evidence is unavailable; package creation is blocked.',['status'=>503,'external_execution_authorized'=>false]);if(is_array($old))return $old+['idempotent_replay'=>true];
  $ok=$wpdb->insert(Tables::pod_authorization_packages(),['order_id'=>$orderId,'render_evidence_id'=>$renderEvidenceId,'provider_mapping_id'=>(int)$render['provider_mapping_id'],'ownership_mapping_id'=>(int)$scope['id'],'readiness_hash'=>$readinessHash,'package_hash'=>$packageHash,'state'=>'REVIEW_REQUIRED','approved_by'=>0,'approved_at'=>null,'external_execution_authorized'=>0,'external_execution_performed'=>0,'created_at'=>current_time('mysql',true)]);
  if($ok!==1){$wpdb->last_error='';$wpdb->flush();$queryResult=$wpdb->query($wpdb->prepare('SELECT * FROM '.Tables::pod_authorization_packages().' WHERE package_hash=%s',$packageHash));if($queryResult===false||!empty($wpdb->last_error))return new WP_Error('authorization_evidence_unavailable','Production authorization query failed closed.',['status'=>503,'retry_permitted'=>false,'external_execution_authorized'=>false]);$winner=(isset($wpdb->last_result[0]) ? (array) $wpdb->last_result[0] : null);if(!empty($wpdb->last_error))return new WP_Error('authorization_package_race_evidence_unavailable','Authorization package insert outcome could not be reconciled; do not retry automatically.',['status'=>503,'retry_permitted'=>false,'external_execution_authorized'=>false]);if(is_array($winner))return $winner+['idempotent_replay'=>true];return new WP_Error('authorization_package_persistence_failed','Production authorization package could not be persisted.',['status'=>500,'retry_permitted'=>false,'external_execution_authorized'=>false]);}
  $wpdb->last_error='';$wpdb->flush();$queryResult=$wpdb->query($wpdb->prepare('SELECT * FROM '.Tables::pod_authorization_packages().' WHERE id=%d',(int)$wpdb->insert_id));if($queryResult===false||!empty($wpdb->last_error))return new WP_Error('authorization_evidence_unavailable','Production authorization query failed closed.',['status'=>503,'retry_permitted'=>false,'external_execution_authorized'=>false]);$created=(isset($wpdb->last_result[0]) ? (array) $wpdb->last_result[0] : null);if(!is_array($created)||!empty($wpdb->last_error))return new WP_Error('authorization_package_confirmation_unavailable','Authorization package was persisted but confirmation evidence is unavailable; do not retry automatically.',['status'=>503,'retry_permitted'=>false,'external_execution_authorized'=>false]);return $created;
 }
 public function approveForReview(int $id):array|WP_Error{
  global $wpdb;$reviewer=get_current_user_id();if($reviewer<1||!current_user_can('manage_digiforge_pod'))return new WP_Error('authorization_reviewer_required','Authenticated human reviewer required.',['status'=>403]);$now=current_time('mysql',true);
  $wpdb->last_error='';$package=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Tables::pod_authorization_packages().' WHERE id=%d',$id),ARRAY_A);if($wpdb->last_error!==''||!is_array($package))return new WP_Error('authorization_evidence_unavailable','Current package evidence is required.',['status'=>503,'retry_permitted'=>false]);
  $wpdb->last_error='';$render=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Tables::pod_render_evidence().' WHERE id=%d AND review_status=%s AND reviewed_by>0 AND reviewed_at IS NOT NULL',(int)$package['render_evidence_id'],'APPROVED'),ARRAY_A);if($wpdb->last_error!==''||!is_array($render))return new WP_Error('authorization_render_required','Current approved render is required.',['status'=>409]);$certified=(new RenderArtifactVerifier())->assertCertified($render);if($certified instanceof WP_Error)return $certified;
  $readiness=(new OrderRepository())->readiness((int)$package['order_id']);if($readiness instanceof WP_Error)return $readiness;if(empty($readiness['ready'])||!hash_equals((string)$package['readiness_hash'],hash('sha256',(string)wp_json_encode($readiness))))return new WP_Error('authorization_readiness_conflict','Package readiness has changed; a new review package is required.',['status'=>409]);$scope=(new BusinessScopeRepository())->assertActiveOwnershipForMapping((int)$package['provider_mapping_id']);if($scope instanceof WP_Error)return $scope;if((int)$scope['id']!==(int)$package['ownership_mapping_id'])return new WP_Error('authorization_ownership_conflict','Current ownership must match the immutable package.',['status'=>409]);
  $wpdb->last_error='';$ok=$wpdb->update(Tables::pod_authorization_packages(),['state'=>'APPROVED_PACKAGE','approved_by'=>$reviewer,'approved_at'=>$now],['id'=>$id,'state'=>'REVIEW_REQUIRED','external_execution_authorized'=>0,'external_execution_performed'=>0]);
  if($ok!==1){if(!empty($wpdb->last_error))return new WP_Error('authorization_review_persistence_failed','Authorization review could not be persisted.',['status'=>503,'retry_permitted'=>false,'external_execution_authorized'=>false]);return new WP_Error('authorization_review_conflict','Authorization package must be pending review and cannot be overwritten.',['status'=>409]);}
  $wpdb->last_error='';$wpdb->flush();$queryResult=$wpdb->query($wpdb->prepare('SELECT * FROM '.Tables::pod_authorization_packages().' WHERE id=%d',$id));if($queryResult===false||!empty($wpdb->last_error))return new WP_Error('authorization_evidence_unavailable','Production authorization query failed closed.',['status'=>503,'retry_permitted'=>false,'external_execution_authorized'=>false]);$approved=(isset($wpdb->last_result[0]) ? (array) $wpdb->last_result[0] : null);if(!is_array($approved)||!empty($wpdb->last_error))return new WP_Error('authorization_review_confirmation_unavailable','Authorization review update completed but confirmation evidence is unavailable; do not retry automatically.',['status'=>503,'retry_permitted'=>false,'external_execution_authorized'=>false]);return $approved;
 }
}
