<?php
declare(strict_types=1);
namespace DigiForge\POD;use DigiForge\Database\Tables;use WP_Error;
final class ReconciliationAcknowledgementRepository{
 public static function save(array $record):array|WP_Error{
  if(($record['state']??'')!=='RECONCILIATION_ACKNOWLEDGED'||!is_array($record['acknowledgement']??null))return new WP_Error('reconciliation_ack_state','Valid acknowledgement evidence required.',['status'=>400]);
  $a=$record['acknowledgement'];$hash=strtolower((string)($record['acknowledgement_hash']??''));$rh=strtolower((string)($a['reconciliation_hash']??''));$auth=strtolower((string)($a['authorization_hash']??''));$unknown=strtolower((string)($a['unknown_hash']??''));$reviewer=(int)($a['reviewed_by']??0);$resolution=(string)($a['resolution_state']??'');$decision=(string)($a['decision']??'');
  $validDecision=($resolution==='PRINTIFY_RECONCILIATION_CONFIRMED'&&$decision==='ACKNOWLEDGE_CONFIRMED')||($resolution==='PRINTIFY_RECONCILIATION_NOT_CONFIRMED'&&$decision==='ACKNOWLEDGE_NOT_CONFIRMED');
  if(!preg_match('/^[a-f0-9]{64}$/',$hash)||!preg_match('/^[a-f0-9]{64}$/',$rh)||!preg_match('/^[a-f0-9]{64}$/',$auth)||!preg_match('/^[a-f0-9]{64}$/',$unknown)||$reviewer<1||!$validDecision||($a['retry_permitted']??null)!==false||($a['external_execution_authorized']??null)!==false)return new WP_Error('reconciliation_ack_binding','Acknowledgement binding is invalid.',['status'=>409]);
  global $wpdb;$table=Tables::pod_reconciliation_acknowledgements();$wpdb->last_error='';$persisted=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Tables::pod_printify_reconciliations().' WHERE reconciliation_hash=%s LIMIT 1',$rh),ARRAY_A);
  if(!empty($wpdb->last_error))return new WP_Error('reconciliation_ack_evidence_unavailable','Persisted reconciliation evidence could not be read.',['status'=>503,'retry_permitted'=>false,'external_execution_authorized'=>false]);if(!is_array($persisted)||!hash_equals(strtolower((string)$persisted['authorization_hash']),$auth)||!hash_equals(strtolower((string)$persisted['unknown_hash']),$unknown)||(string)$persisted['resolution_state']!==$resolution)return new WP_Error('reconciliation_ack_evidence_missing','Acknowledgement must bind exact persisted reconciliation evidence.',['status'=>409]);
  $wpdb->last_error='';$existing=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.$table.' WHERE reconciliation_hash=%s LIMIT 1',$rh),ARRAY_A);if(!empty($wpdb->last_error))return new WP_Error('reconciliation_ack_evidence_unavailable','Existing acknowledgement evidence could not be read.',['status'=>503,'retry_permitted'=>false,'external_execution_authorized'=>false]);if(is_array($existing))return hash_equals((string)$existing['acknowledgement_hash'],$hash)?$existing:new WP_Error('reconciliation_ack_conflict','Reconciliation already has different acknowledgement evidence.',['status'=>409]);
  $row=['authorization_hash'=>$auth,'unknown_hash'=>$unknown,'reconciliation_hash'=>$rh,'resolution_state'=>$resolution,'decision'=>$decision,'reviewed_by'=>$reviewer,'acknowledgement_hash'=>$hash,'created_at'=>current_time('mysql',true)];
  if($wpdb->insert($table,$row)===false){$wpdb->last_error='';$winner=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.$table.' WHERE reconciliation_hash=%s LIMIT 1',$rh),ARRAY_A);if(!empty($wpdb->last_error))return new WP_Error('reconciliation_ack_confirmation_unavailable','Acknowledgement outcome is uncertain; do not retry automatically.',['status'=>503,'retry_permitted'=>false,'external_execution_authorized'=>false]);if(is_array($winner)&&hash_equals((string)$winner['acknowledgement_hash'],$hash))return $winner;return new WP_Error('reconciliation_ack_store','Acknowledgement could not be persisted.',['status'=>409]);}$row['id']=(int)$wpdb->insert_id;return $row;
 }
}
