<?php
declare(strict_types=1);
namespace DigiForge\Portal;
use DigiForge\Database\Tables;
use WP_Error;
/** Append-only versioned shop/workflow policy evidence. Saving policy is not execution authorization. */
final class ScopedCapabilityPolicyRepository {
 public function append(string $shop,string $workflow,string $capability,bool $enabled):array|WP_Error {
  global $wpdb;$shop=sanitize_key($shop);$workflow=sanitize_key($workflow);$capability=sanitize_key($capability);if($shop===''||$workflow===''||$capability==='')return new WP_Error('invalid_scoped_policy','Shop, workflow and capability are required.');
  $wpdb->last_error='';$prev=$wpdb->get_row($wpdb->prepare('SELECT policy_version,policy_hash FROM '.Tables::scoped_capability_policies().' WHERE shop_key=%s AND workflow_key=%s AND capability=%s ORDER BY policy_version DESC LIMIT 1',$shop,$workflow,$capability),ARRAY_A);if(!empty($wpdb->last_error))return new WP_Error('scoped_policy_predecessor_unavailable','Scoped policy predecessor evidence is unavailable.');$version=is_array($prev)?((int)$prev['policy_version']+1):1;$previous=is_array($prev)?(string)$prev['policy_hash']:'';
  $canonical=wp_json_encode(['shop_key'=>$shop,'workflow_key'=>$workflow,'capability'=>$capability,'enabled'=>$enabled,'policy_version'=>$version,'previous_policy_hash'=>$previous]);$hash=hash('sha256',(string)$canonical);$now=current_time('mysql',true);
  $ok=$wpdb->insert(Tables::scoped_capability_policies(),['shop_key'=>$shop,'workflow_key'=>$workflow,'capability'=>$capability,'enabled'=>$enabled?1:0,'policy_version'=>$version,'policy_hash'=>$hash,'previous_policy_hash'=>$previous,'created_by'=>get_current_user_id(),'created_at'=>$now]);if($ok!==1)return new WP_Error('scoped_policy_persistence_failed','Scoped policy evidence could not be persisted.');
  return ['id'=>(int)$wpdb->insert_id,'shop_key'=>$shop,'workflow_key'=>$workflow,'capability'=>$capability,'enabled'=>$enabled,'policy_version'=>$version,'policy_hash'=>$hash,'previous_policy_hash'=>$previous,'read_only_evidence'=>true,'external_execution_authorized'=>false];
 }
 public function latest(string $shop,string $workflow,string $capability, ?string &$queryState=null):?array {global $wpdb;$wpdb->last_error='';$r=$wpdb->get_row($wpdb->prepare('SELECT id,shop_key,workflow_key,capability,enabled,policy_version,policy_hash,previous_policy_hash,created_by,created_at FROM '.Tables::scoped_capability_policies().' WHERE shop_key=%s AND workflow_key=%s AND capability=%s ORDER BY policy_version DESC LIMIT 1',sanitize_key($shop),sanitize_key($workflow),sanitize_key($capability)),ARRAY_A);if(!empty($wpdb->last_error)){$queryState='UNAVAILABLE';return null;}$queryState='AVAILABLE';if(!is_array($r))return null;$r['read_only_evidence']=true;$r['external_execution_authorized']=false;return $r;}
 /** Bounded read-only policy history; newest first. */
 public function recent(string $shop='',string $workflow='',int $limit=50, ?string &$queryState=null):array {global $wpdb;$limit=max(1,min(200,$limit));$where=[];$args=[];if($shop!==''){$where[]='shop_key=%s';$args[]=sanitize_key($shop);}if($workflow!==''){$where[]='workflow_key=%s';$args[]=sanitize_key($workflow);}$sql='SELECT id,shop_key,workflow_key,capability,enabled,policy_version,policy_hash,previous_policy_hash,created_by,created_at FROM '.Tables::scoped_capability_policies().($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY id DESC LIMIT %d';$args[]=$limit;$wpdb->last_error='';$rows=$wpdb->get_results($wpdb->prepare($sql,...$args),ARRAY_A);if(!is_array($rows)||!empty($wpdb->last_error)){$queryState='UNAVAILABLE';return [];}$queryState='AVAILABLE';return array_map(static function(array $r):array{$r['read_only_evidence']=true;$r['retry_permitted']=false;$r['external_execution_authorized']=false;return $r;},$rows);}
 public function current(int $limit=100, ?string &$queryState=null):array {global $wpdb;$limit=max(1,min(200,$limit));$table=Tables::scoped_capability_policies();$sql="SELECT p.id,p.shop_key,p.workflow_key,p.capability,p.enabled,p.policy_version,p.policy_hash,p.previous_policy_hash,p.created_by,p.created_at FROM $table p INNER JOIN (SELECT shop_key,workflow_key,capability,MAX(policy_version) latest_version FROM $table GROUP BY shop_key,workflow_key,capability) x ON p.shop_key=x.shop_key AND p.workflow_key=x.workflow_key AND p.capability=x.capability AND p.policy_version=x.latest_version ORDER BY p.shop_key,p.workflow_key,p.capability LIMIT %d";$wpdb->last_error='';$rows=$wpdb->get_results($wpdb->prepare($sql,$limit),ARRAY_A);if(!is_array($rows)||!empty($wpdb->last_error)){$queryState='UNAVAILABLE';return [];}$queryState='AVAILABLE';return array_map(static function(array $r):array{$r['read_only_evidence']=true;$r['external_execution_authorized']=false;return $r;},$rows);}
}